import type { Call, RepSpec } from "../sim/lane";
import type { PovId } from "../sim/pov";
import { LINES } from "../voice/lines";
import type { Lesson, LessonDoor, LessonFamily } from "./course";

type Shot = { pov: PovId; tag: string };

const SHOTS: Record<LessonFamily, [Shot, Shot]> = {
  edge: [
    { pov: "edge-wide", tag: "PEEKER" },
    { pov: "edge-hold", tag: "HOLDER" },
  ],
  swing: [
    { pov: "swing-you", tag: "SWING" },
    { pov: "swing-hold", tag: "HOLDER" },
  ],
  choice: [
    { pov: "choice-wide", tag: "WIDE" },
    { pov: "choice-jiggle", tag: "JIGGLE" },
  ],
  isolate: [
    { pov: "isolate-one", tag: "ONE" },
    { pov: "isolate-both", tag: "BOTH" },
  ],
};

type Draft = {
  id: string;
  index: string;
  title: string;
  summary: string;
  family: LessonFamily;
  door: LessonDoor;
  idea: string;
  good: string;
  miss: string;
  them: string;
  brief: string;
  cue: string;
  reps: { call: Call; enemy: "close" | "deep" }[];
};

function say(id: string, text: string): string {
  LINES[id] = { id, text };
  return id;
}

function build(draft: Draft): Lesson {
  const cueId = say(`${draft.id}-cue`, draft.cue);
  const [you, them] = SHOTS[draft.family];
  const reps: RepSpec[] = draft.reps.map((rep) => ({ ...rep, cueId }));
  return {
    id: draft.id,
    index: draft.index,
    title: draft.title,
    summary: draft.summary,
    family: draft.family,
    door: draft.door,
    explain: [],
    showBeats: [],
    pov: [
      { id: you.pov, tag: you.tag, lines: [say(`${draft.id}-idea`, draft.idea), say(`${draft.id}-good`, draft.good)] },
      { id: them.pov, tag: them.tag, lines: [say(`${draft.id}-miss`, draft.miss), say(`${draft.id}-them`, draft.them)] },
    ],
    brief: say(`${draft.id}-brief`, draft.brief),
    control: "A and D along the angle. Mouse looks. Click shoots. Tap the other strafe key to stop.",
    reps,
    isolate: draft.family === "isolate",
  };
}

const swing = (enemy: "close" | "deep" = "close") => ({ call: "swing" as const, enemy });
const jiggle = { call: "jiggle" as const, enemy: "close" as const };
const hold = { call: "hold" as const, enemy: "close" as const };
const iso = { call: "isolate" as const, enemy: "close" as const };

const DRAFTS: Draft[] = [
  {
    id: "headline",
    index: "05",
    title: "Head Line",
    summary: "The crosshair is already at head height before your shoulder clears.",
    family: "swing",
    door: "theory",
    idea: "Their head lives on the horizon. Put the crosshair there before you ever touch the strafe key.",
    good: "You clear, and the head is already in the sight. You are not looking for it.",
    miss: "The usual miss is finding the head after you are out. By then they have already shot.",
    them: "From here, I watch your eyes climb up to me. That climb is the whole fight.",
    brief: "Head height first. Then a fast wide swing, stop, and one shot. Click the range to arm.",
    cue: "Head line. Then swing.",
    reps: [swing(), swing(), swing("deep"), swing(), swing("deep"), swing()],
  },
  {
    id: "thestop",
    index: "06",
    title: "The Stop",
    summary: "Clear, kill your speed with the other key, then shoot.",
    family: "swing",
    door: "theory",
    idea: "A swing is fast until the shot. Tap the other strafe key, let the speed die, then click.",
    good: "You stop on their head. The bullet leaves after the strafe is dead.",
    miss: "Clicking while you are still flying throws it wide. Speed is not the shot.",
    them: "I see the swing, then a shot that leaves before you ever sit still.",
    brief: "Fast out, other key to stop, then the click. Click the range to arm.",
    cue: "Clear. Stop. Shoot.",
    reps: [swing(), swing("deep"), swing(), swing("deep"), swing(), swing("deep")],
  },
  {
    id: "offpixel",
    index: "07",
    title: "Off the Pixel",
    summary: "Come out wide enough that they are still aimed at the wall.",
    family: "edge",
    door: "theory",
    idea: "A wide swing shows up off the pixel they are holding. You see them first.",
    good: "You are on their head while their crosshair is still kissing the corner.",
    miss: "Creep the corner and you walk onto that pixel. Then they do not even flick.",
    them: "If you appear where I am already aimed, I do not have to move.",
    brief: "Leave fast and wide. Be on the head before the corner clears you. Click the range to arm.",
    cue: "Wide. Off their pixel.",
    reps: [swing(), swing(), hold, swing("deep"), hold, swing()],
  },
  {
    id: "flash",
    index: "08",
    title: "Shoulder Flash",
    summary: "A jiggle is a short look. Shoulder out, then you are gone.",
    family: "choice",
    door: "theory",
    idea: "A jiggle is not a fight. You show a shoulder, you see if they are there, you come back.",
    good: "Out and back before their click. You got the information and kept the timing.",
    miss: "Stay out and it stops being a look. It becomes a peek, and they get the shot.",
    them: "I only need you to hesitate. If the shoulder stays, I shoot it.",
    brief: "Short strafe past the edge and straight back. Do not take the fight. Click the range to arm.",
    cue: "Shoulder out. Come back.",
    reps: [jiggle, jiggle, jiggle, swing(), jiggle, jiggle],
  },
  {
    id: "thegap",
    index: "09",
    title: "The Gap",
    summary: "The open space between two angles is where you die for free.",
    family: "isolate",
    door: "theory",
    idea: "If two people can see you, you can only shoot one. The other one is free.",
    good: "Stay tight to the first wall. The far angle is still a wall, not a person.",
    miss: "Step into the gap and both of them have you. You never even fought the second.",
    them: "I am the one you were not looking at. From here, you are just standing in the open.",
    brief: "Near angle first. Do not open the far one until the close one is dead. Click the range to arm.",
    cue: "Stay out of the gap.",
    reps: [iso, iso, iso, iso],
  },
  {
    id: "deepplace",
    index: "10",
    title: "Deep Place",
    summary: "A deeper hold means the crosshair starts wider, still at head height.",
    family: "swing",
    door: "theory",
    idea: "Deep does not mean a bigger flick. It means you place wider before you move.",
    good: "The crosshair is already where that head will be. The wall slides off them.",
    miss: "Place for the close angle and the deep one makes you hunt after you are exposed.",
    them: "You cleared my angle still looking at the wrong spot. I watched you correct.",
    brief: "Deep hold. Place wider, head height, then the same swing. Click the range to arm.",
    cue: "Place wider. Then go.",
    reps: [swing("deep"), swing("deep"), swing(), swing("deep"), swing("deep"), swing("deep")],
  },
  {
    id: "firstlook",
    index: "11",
    title: "First Look",
    summary: "The swinger sees the holder first. That gap is the whole edge.",
    family: "edge",
    door: "theory",
    idea: "You pick the moment. On their screen you show up late, and you are already aimed.",
    good: "Fast and wide. You see the head while they are still on the corner.",
    miss: "Slow, and the gap flips. They see you the whole way out.",
    them: "When you do it right, I am late. When you creep, I am early.",
    brief: "Take the first look. Swing it, do not donate it. Click the range to arm.",
    cue: "You see them first.",
    reps: [swing(), swing("deep"), hold, swing(), hold, swing()],
  },
  {
    id: "posted",
    index: "12",
    title: "Still Posted",
    summary: "Holding the edge loses to a fast wide swing.",
    family: "edge",
    door: "theory",
    idea: "Posting on a pixel feels safe. Against a swing, you are the one reacting.",
    good: "You stay and you feel how little time you get. That loss is the lesson.",
    miss: "A flick off the edge is a guess. It dies the next time they swing somewhere else.",
    them: "I leave the corner already aimed. You are still where you posted.",
    brief: "When it says hold, stay on the angle and watch the swing come in. Click the range to arm.",
    cue: "Hold it. Feel the swing.",
    reps: [hold, swing(), hold, swing("deep"), hold, swing()],
  },
  {
    id: "clearit",
    index: "13",
    title: "Clear It",
    summary: "The wall comes off their head. Your crosshair does not go hunting.",
    family: "swing",
    door: "theory",
    idea: "You are not slicing out to look. You already know who is there. You clear them.",
    good: "Crosshair still, feet fast, then the stop, then one shot.",
    miss: "Crosshair glued to the wall means you flick after you are already a target.",
    them: "I see you find me. A clear does not look like a search.",
    brief: "Keep the crosshair on the pip. Strafe, stop, shoot. Click the range to arm.",
    cue: "Clear the angle.",
    reps: [swing(), swing(), swing("deep"), swing(), swing("deep"), swing()],
  },
  {
    id: "onefight",
    index: "14",
    title: "One Fight",
    summary: "One crosshair, one person. The other angle stays closed.",
    family: "isolate",
    door: "theory",
    idea: "Isolate means only one threat can see you. You pre-aim that one.",
    good: "Tight to the first edge. Clear it. Then place for the next.",
    miss: "Open both and the one off your crosshair shoots you for free.",
    them: "You were fighting someone else. I already had the shot.",
    brief: "One fight at a time. Near, then far. Click the range to arm.",
    cue: "One fight. Then the next.",
    reps: [iso, iso, iso, iso],
  },
  {
    id: "justlook",
    index: "15",
    title: "Just a Look",
    summary: "Look when you need information. Swing when you are ready to shoot.",
    family: "choice",
    door: "theory",
    idea: "Do not jiggle a kill, and do not wide-swing a corner you only needed to see.",
    good: "The call is the whole rep. Swing takes the fight. Jiggle takes the look.",
    miss: "Mix them up and you either give the timing away or you overcommit a look.",
    them: "I can tell which one you meant. A look leaves. A swing stays.",
    brief: "I will only ask for a look here. Shoulder, see them, get back. Click the range to arm.",
    cue: "Just a look. Get back.",
    reps: [jiggle, jiggle, swing(), jiggle, jiggle, swing("deep")],
  },
  {
    id: "lateedge",
    index: "16",
    title: "Late on the Edge",
    summary: "The holder is late. That is what a fast swing feels like from their side.",
    family: "edge",
    door: "theory",
    idea: "You see them first because you chose the moment. They only get to react.",
    good: "Wide, fast, already at head height. Their crosshair is still on the wall you left.",
    miss: "Anything slower hands that moment back. Then you are the one who is late.",
    them: "I am holding a pixel. You appear off it, and I am already behind.",
    brief: "Make them late. Swing it wide. Click the range to arm.",
    cue: "Make them late.",
    reps: [swing(), swing("deep"), hold, swing(), swing("deep"), hold],
  },
  {
    id: "arrive",
    index: "01",
    title: "Arrive First",
    summary: "Be on the head, then swing. The arrival happens before the fight.",
    family: "swing",
    door: "course",
    idea: "The click is an arrival. In a fight, that arrival happens before you leave the wall.",
    good: "Head in the sight, then the feet. You do not arrive out in the open.",
    miss: "You swing and then you look. That order gets you shot.",
    them: "Your crosshair showed up after you did. I was already looking.",
    brief: "Place it, then swing, then stop, then shoot. Click the range to arm.",
    cue: "Arrive, then leave.",
    reps: [swing(), swing(), swing("deep"), swing(), swing(), swing("deep")],
  },
  {
    id: "oneclick",
    index: "02",
    title: "One Click",
    summary: "One shot after the stop. Misses do not buy time.",
    family: "swing",
    door: "course",
    idea: "After you stop, you get one click. A spray keeps you in their window.",
    good: "Stopped, on the head, one shot. Then you are done with the angle.",
    miss: "Extra clicks while you are out are just you standing there.",
    them: "You kept shooting and none of them were on me. I waited.",
    brief: "Stop, then one click. Do not spray the angle. Click the range to arm.",
    cue: "One click after the stop.",
    reps: [swing(), swing("deep"), swing(), swing(), swing("deep"), swing()],
  },
  {
    id: "horizon",
    index: "03",
    title: "On the Horizon",
    summary: "Eyes on the horizon. Their head is there, not on the floor.",
    family: "swing",
    door: "course",
    idea: "Head height is the horizon. Drop your eyes and you are aiming at a chest.",
    good: "The pip, their head, and your crosshair sit on the same line.",
    miss: "A low crosshair means you clear the angle and still have to climb.",
    them: "You were looking at my chest. I never had to duck.",
    brief: "Keep it on the horizon the whole swing. Click the range to arm.",
    cue: "Eyes on the horizon.",
    reps: [swing(), swing(), swing("deep"), swing(), swing("deep"), swing()],
  },
  {
    id: "counter",
    index: "04",
    title: "Counter",
    summary: "The other strafe key is the stop. Then you shoot.",
    family: "swing",
    door: "course",
    idea: "Counter-strafe is how a swing becomes a shot. Opposite key, speed dies, click.",
    good: "You are still when the bullet leaves. The head was already there.",
    miss: "No stop, and the shot throws wide of the head you had.",
    them: "You were still moving when you fired. I watched it miss.",
    brief: "Tap the other key. Feel the stop. Then click. Click the range to arm.",
    cue: "Other key. Then click.",
    reps: [swing(), swing(), swing("deep"), swing(), swing(), swing("deep")],
  },
  {
    id: "howwide",
    index: "05",
    title: "How Wide",
    summary: "Wide enough to leave their pixel. Not a tour of the open.",
    family: "edge",
    door: "course",
    idea: "Wide means off their crosshair, not across the whole site. You still have a shot.",
    good: "You appear where they are not aimed, and you are already on the head.",
    miss: "Too tight and you are on the pixel. Too lost and you never shoot.",
    them: "I want you on my pixel. Come out beside it.",
    brief: "Swing wide of the corner and take the shot. Click the range to arm.",
    cue: "Wide of the pixel.",
    reps: [swing(), swing("deep"), swing(), hold, swing(), swing("deep")],
  },
  {
    id: "ashoulder",
    index: "06",
    title: "A Shoulder",
    summary: "The look is a shoulder, not your whole body.",
    family: "choice",
    door: "course",
    idea: "If they can see your whole body, you stayed. A look is a shoulder and a return.",
    good: "They get a flash. You are already going back into the wall.",
    miss: "A full swing on a look gives the timing away and never needs to.",
    them: "I saw all of you. A look should have been a shoulder.",
    brief: "Shoulder only. Out and back. Click the range to arm.",
    cue: "Just the shoulder.",
    reps: [jiggle, jiggle, jiggle, jiggle, swing(), jiggle],
  },
  {
    id: "backwall",
    index: "07",
    title: "Back to the Wall",
    summary: "The return is part of the jiggle. You are not done out there.",
    family: "choice",
    door: "course",
    idea: "A jiggle ends in cover. If you are still out, it is a peek.",
    good: "You saw them and the wall had you again before the shot.",
    miss: "Hesitate on the way back and they get the timing you just stole.",
    them: "You saw me and then you stayed to think. That is when I shoot.",
    brief: "See them and get back in the wall. Click the range to arm.",
    cue: "See them. Back in.",
    reps: [jiggle, jiggle, swing(), jiggle, jiggle, jiggle],
  },
  {
    id: "nearfar",
    index: "08",
    title: "Near Then Far",
    summary: "The close angle dies first. Then you place for the next edge.",
    family: "isolate",
    door: "course",
    idea: "Slice the near one while the far one is still behind a wall.",
    good: "Close fight, already aimed. Then the next edge, same swing.",
    miss: "Take the far one first and the close one shoots you in the side.",
    them: "You looked past me. I was the close one, and I was still alive.",
    brief: "Near, then far. Do not skip the close angle. Click the range to arm.",
    cue: "Near one, then the far.",
    reps: [iso, iso, iso, iso],
  },
  {
    id: "staytight",
    index: "09",
    title: "Stay Tight",
    summary: "Hug the first wall so the second angle cannot see you.",
    family: "isolate",
    door: "course",
    idea: "Tight to the wall is how the far player stays blind.",
    good: "One crosshair, one body in the open. The other angle is still closed.",
    miss: "A wide step opens both. You can only shoot one of them.",
    them: "You stepped wide and I had a free shot at your side.",
    brief: "Stay tight until the first angle is clear. Click the range to arm.",
    cue: "Tight to the wall.",
    reps: [iso, iso, iso, iso],
  },
  {
    id: "matchcall",
    index: "10",
    title: "Match the Call",
    summary: "The cue is the rep. Swing or jiggle, and nothing else.",
    family: "choice",
    door: "course",
    idea: "I will call the tool. Your job is to do that tool and not the other one.",
    good: "Swing when it is a fight. Jiggle when it is information.",
    miss: "The miss is doing the other one. A look that commits, or a fight that flakes.",
    them: "I can see which tool you brought. Bring the one I asked for.",
    brief: "Swing reps you finish. Jiggle reps you leave. Click the range to arm.",
    cue: "Do the one I call.",
    reps: [swing(), jiggle, jiggle, swing("deep"), jiggle, swing()],
  },
  {
    id: "dontflake",
    index: "11",
    title: "Don't Flake",
    summary: "If the call is a fight, you finish it. A jiggle there gives the timing away.",
    family: "choice",
    door: "course",
    idea: "Do not jiggle a kill. You show them the timing and you never take the shot.",
    good: "The fight is a swing. Fast, wide, head height, stop, click.",
    miss: "A shy peek on a swing call is how you donate the round.",
    them: "You showed me you were coming, then you left. Now I know.",
    brief: "These are fights. Commit, or do not peek. Click the range to arm.",
    cue: "Finish the fight.",
    reps: [swing(), swing("deep"), jiggle, swing(), swing("deep"), swing()],
  },
  {
    id: "theirpixel",
    index: "12",
    title: "Their Pixel",
    summary: "The pixel they hold is where a slow peek dies.",
    family: "edge",
    door: "course",
    idea: "They are aimed at one pixel on the corner. Your job is to not be that pixel.",
    good: "You show up off it, already at head height, and you see them first.",
    miss: "Creep and you become the pixel. They click. They do not flick.",
    them: "You walked into the only place I was looking.",
    brief: "Do not be their pixel. Swing wide of it. Click the range to arm.",
    cue: "Not their pixel.",
    reps: [swing(), hold, swing("deep"), swing(), hold, swing()],
  },
  {
    id: "dontlive",
    index: "13",
    title: "Don't Live There",
    summary: "If you are out, the shot is now. Do not stand in their window.",
    family: "swing",
    door: "course",
    idea: "Exposure is a moment, not a place you live. Clear, stop, shoot, or get back.",
    good: "The shot happens as the head clears. You are not camping their angle.",
    miss: "Step out and wait, and they have all day.",
    them: "You stood in my window. I did not have to rush.",
    brief: "Out, stop, shoot. Do not live on the angle. Click the range to arm.",
    cue: "Out, then the shot.",
    reps: [swing(), swing(), swing("deep"), swing(), swing("deep"), swing()],
  },
  {
    id: "slice",
    index: "14",
    title: "Slice",
    summary: "Slice the close angle. The far one is still a wall.",
    family: "isolate",
    door: "course",
    idea: "A slice is a swing that only opens one angle. Same rules. Head, speed, stop, shot.",
    good: "Near one dies before the far one can see your shoulder.",
    miss: "A wide slice is just standing in both of them.",
    them: "You opened my angle while you were still fighting the other one.",
    brief: "Slice the close one. Then the next. Click the range to arm.",
    cue: "Slice the close one.",
    reps: [iso, iso, iso, iso],
  },
  {
    id: "already",
    index: "15",
    title: "Already There",
    summary: "The crosshair is on the head before the feet move.",
    family: "swing",
    door: "course",
    idea: "Already there means the fight is aimed before it starts. Feet are just the clear.",
    good: "Place, swing, stop, shoot. One motion. No search.",
    miss: "If you look after you move, you are late to your own swing.",
    them: "You cleared and then you looked for me. I was not lost.",
    brief: "Be there before you move. Then swing it. Click the range to arm.",
    cue: "Already on the head.",
    reps: [swing(), swing("deep"), swing(), swing(), swing("deep"), swing()],
  },
  {
    id: "farshut",
    index: "16",
    title: "Far Stays Shut",
    summary: "The far angle stays closed until you decide to open it.",
    family: "isolate",
    door: "course",
    idea: "You choose when the second person can see you. Until then, they are a wall.",
    good: "First fight is alone. Then you place, and you open the next one.",
    miss: "Open it early and you fight two guns with one crosshair.",
    them: "I should not see you yet. When I do, you are already dead to the close one.",
    brief: "Keep the far angle shut until the near one is done. Click the range to arm.",
    cue: "Far one stays shut.",
    reps: [iso, iso, iso, iso],
  },
];

export const MORE_LESSONS: Lesson[] = DRAFTS.map(build);
