/* Couch To Front Office: realistic NHL Draft module (draft.js).
   Installed from index.html via CTFODraft.install(deps) just before init().
   Covers draft order + lottery, the live draft engine, CPU picks, draft rights/ELCs,
   and prospect classes (bundled real classes when present, else a seeded fictional generator). */
(function(){
'use strict';
var D={version:'ctfo-draft-1'},X=null,O={};window.CTFODraft=D;
var ODDS=[18.5,13.5,11.5,9.5,8.5,7.5,6.5,6.0,5.0,3.5,3.0,2.5,2.0,1.5,0.5,0.5];
var CLASS_SIZE=280,READY=77;
function T(){return window.CTFO_DRAFT_DATA;}
function hash(s){var h=2166136261>>>0;s=String(s);for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0;}return h;}
function rng(seed){var a=hash(seed)||1;return function(){a=(a+0x6D2B79F5)>>>0;var t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function gauss(r){var u=Math.max(1e-9,r()),v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
function pickW(r,list){var tot=0;list.forEach(function(x){tot+=x[1];});var t=r()*tot;for(var i=0;i<list.length;i++){t-=list[i][1];if(t<=0)return list[i][0];}return list[list.length-1][0];}
function one(r,a){return a[Math.floor(r()*a.length)];}
function cl(n,a,b){return Math.max(a,Math.min(b,n));}
function iso(y,m,d){return y+'-'+String(m).padStart(2,'0')+'-'+String(d).padStart(2,'0');}
function ageAt(dob,date){if(!dob)return null;var a=dob.split('-').map(Number),b=date.split('-').map(Number),age=b[0]-a[0];if(b[1]<a[1]||(b[1]===a[1]&&b[2]<a[2]))age--;return age;}
function seedOf(g){if(!g.draftSeed){var f=(g.prospects||[]).find(function(p){return p.ctfoSeed;});g.draftSeed=f?f.ctfoSeed:'save-'+Math.random().toString(36).slice(2,10);}return g.draftSeed;}
function startYear(g){return Number(g&&g.startYear)||2026;}
function draftYearOf(g){return Number(g.offseason&&g.offseason.year)||startYear(g)+Number(g.season||1);}
function club(g,id){return id===g.team?g:X.leagueClub(g,id);}
function teamIds(){return X.teams.map(function(t){return t.id;});}
function nm(id){return X.team(id).name;}
function leagueType(p){var L=T().LEAGUES[p.leagueCode]||null;return L?L.type:(/OHL|WHL|QMJHL/.test(p.league||'')?'CHL':/NCAA/.test(p.league||'')?'NCAA':/USHL|NTDP|USNTDP/.test(p.league||'')?'NCAA_BOUND':'EURO');}
function money(n){return '$'+(n/1e6).toFixed(n%10000?3:2).replace(/0$/,'')+'M';}

/* ---------- prospect classes ---------- */
function curvePot(r,rank,pos){var sd=rank<=10?2:3,p=96-4.6*Math.log(rank)+gauss(r)*sd;if(rank>64&&r()<0.04)p+=5+r()*4;if(pos==='G')p-=1;return Math.round(cl(p,62,97));}
function ovrFrom(r,pot,age,pos,rank){var gap={17:21,18:20,19:16,20:13}[age]||12;if(pos==='G')gap+=4;if(rank<=3)gap-=3;return Math.round(cl(pot-gap+gauss(r)*2,45,80));}
function stats(r,p){var L=T().LEAGUES[p.leagueCode]||T().LEAGUES.OHL,q=cl((p.potential-68)/28,0,1),gp=Math.round(L.gp[0]+r()*(L.gp[1]-L.gp[0]));if(p.pos==='G'){var gg=Math.round(gp*0.7);return {season:p.statSeason,gp:gg,svp:+(0.880+0.032*q+gauss(r)*0.006).toFixed(3),gaa:+(3.6-1.3*q+gauss(r)*0.2).toFixed(2)};}var ppg=(L.ppg[0]+(L.ppg[1]-L.ppg[0])*Math.pow(q,1.3))*(p.pos==='D'?0.55:1)*(0.85+r()*0.3),pts=Math.max(0,Math.round(ppg*gp)),g=Math.round(pts*(p.pos==='D'?0.25:0.43+r()*0.12));return {season:p.statSeason,gp:gp,g:g,a:pts-g,pts:pts};}
function uniqueName(r,nat,league,taken){var N=T().NAMES,pool=N[nat]||N.CAN;if(nat==='CAN'&&league==='QMJHL'&&r()<0.6)pool=N.QUE;for(var i=0;i<60;i++){var n=one(r,pool.f)+' '+one(r,pool.l);if(!taken[n]&&!(X.nameTaken&&X.nameTaken(n))){taken[n]=1;if(X.claimName)X.claimName(n);return n;}}var m=one(r,pool.f)+' '+one(r,pool.l)+'-'+one(r,pool.l);taken[m]=1;return m;}
function basePlayer(r,o){var p=X.makePlayer(o.name,o.pos,o.ovr,0,o.age,null,true,r);p.id=o.id;p.potential=o.pot;p.years=0;p.salary=0;p.capHit=0;p.scouted=false;p.generated=!o.real;p.synthetic=!o.real;p.real=!!o.real;p.draftYear=o.year;return p;}
function decorate(p,o){['ctfoDob','shoots','heightCm','weightKg','nationality','league','leagueCode','amateurTeam','stats','statSeason','dataSource','consensusSource'].forEach(function(k){if(o[k]!==undefined)p[k]=o[k];});p.region=p.league;p.level=p.amateurTeam;p.ratingSource='Simulation estimate from draft rank, age and league';p.contractSource='Not signed';return p;}
function fictionalClass(year,seed,g){var r=rng(seed+'|class|'+year),D_=T(),taken={},out=[],bias=gauss(r)*1.2;
 for(var i=0;i<CLASS_SIZE;i++){var rank=i+1,nat=pickW(r,D_.NATIONS.map(function(n){return [n[0],n[1]];})),pos=pickW(r,[['C',25],['LW',15],['RW',15],['D',35],['G',10]]),posFix=(pos==='G'&&rank<=15&&r()<0.85)?(pos=pickW(r,[['C',30],['LW',15],['RW',15],['D',40]])):pos,over=r()<(rank<=20?0.05:0.22),age=over?(r()<0.75?19:20):18,
  lc=pickW(r,D_.LEAGUE_BY_NATION[nat]||D_.LEAGUE_BY_NATION.CAN);if(lc==='CHL')lc=one(r,D_.CHL);if(over&&(nat==='USA'||nat==='CAN')&&r()<0.35)lc='NCAA';
  var by=year-18-(age-18),mo=1+Math.floor(r()*12),dy=1+Math.floor(r()*28),birthY=mo>9||(mo===9&&dy>15)?by-1:by,dob=iso(birthY,mo,dy);
  var pot=Math.round(cl(curvePot(r,rank,pos)+bias,62,97)),realAge=ageAt(dob,iso(year,6,26)),ovr=ovrFrom(r,pot,realAge,pos,rank),
  h=Math.round(pos==='G'?190+gauss(r)*4:(pos==='D'?187:184)+gauss(r)*5),w=Math.round(84+(h-185)*0.9+gauss(r)*5),
  name=uniqueName(r,nat,lc,taken),L=D_.LEAGUES[lc],o={id:'draft-'+year+'-'+(hash(seed)%1e6).toString(36)+'-'+i,name:name,pos:pos,ovr:ovr,age:realAge,pot:pot,year:year,real:false};
  var p=basePlayer(r,o);decorate(p,{ctfoDob:dob,shoots:pos==='G'?(r()<0.85?'L':'R'):(r()<0.62?'L':'R'),heightCm:h,weightKg:w,nationality:nat,league:L.name,leagueCode:lc,amateurTeam:one(r,D_.TEAMS[lc]),statSeason:(year-1)+'-'+String(year).slice(2),dataSource:'Fictional class generated for this save'});
  p.stats=stats(r,p);p.projection=Math.round(cl(pot+gauss(r)*(rank<=10?1.5:rank<=64?2.5:3.5)-(pos==='G'&&rank<=40?2:0),55,99));out.push(p);}
 rankClass(out);return out;}
function realClass(year,seed,data){var r=rng(seed+'|real|'+year),list=(data.players||[]).slice().sort(function(a,b){return (a.consensusRank||9999)-(b.consensusRank||9999);}),out=[];
 list.forEach(function(x,i){var rank=i+1,pos=x.position||'C',dob=x.dob,age=ageAt(dob,iso(year,6,26))||18,pot=curvePot(r,rank,pos),ovr=ovrFrom(r,pot,age,pos,rank);
  var p=basePlayer(r,{id:'draft-'+year+'-ep-'+(x.epId||i),name:x.name,pos:pos,ovr:ovr,age:age,pot:pot,year:year,real:true});
  decorate(p,{ctfoDob:dob,shoots:x.shoots,heightCm:x.heightCm,weightKg:x.weightKg,nationality:x.nationality,league:x.league,leagueCode:x.leagueCode,amateurTeam:x.team,stats:x.stats,statSeason:x.stats&&x.stats.season,dataSource:'Real '+year+' draft class: '+(data.source||'Elite Prospects + public rankings'),consensusSource:x.rankSource});
  p.projection=Math.round(cl(pot+gauss(r)*1.5,55,99));p.consensusRank=x.consensusRank||null;out.push(p);});
 if(out.length<CLASS_SIZE)out=out.concat(fictionalClass(year,seed+'|fill',null).slice(out.length));rankClass(out,true);return out;}
function rankClass(list,keepConsensus){list.slice().sort(function(a,b){if(keepConsensus&&(a.consensusRank||b.consensusRank))return (a.consensusRank||9999)-(b.consensusRank||9999)||b.projection-a.projection;return b.projection-a.projection;}).forEach(function(p,i){p.draftRank=i+1;});}
D.makeProspects=function(seasonNo,id,g){var year=startYear(g)+Number(seasonNo||1),seed=(g&&g.draftSeed)||D._seed||(D._seed='save-'+Math.random().toString(36).slice(2,10));if(g&&!g.draftSeed)g.draftSeed=seed;var data=window.CTFO_DRAFT_CLASSES&&window.CTFO_DRAFT_CLASSES[year],list=data&&data.players&&data.players.length?realClass(year,seed,data):fictionalClass(year,seed,g);list.forEach(function(p){p.ctfoSeed=seed;});if(g){g.draftModelVersion=3;g.draftClassSize=0;g.draftClassStrength='';}return list;};
D.draftClassInfo=function(g){var list=g.prospects||[];if(list.length&&list[0].ctfoSeed&&!g.draftSeed)g.draftSeed=list[0].ctfoSeed;if(list.some(function(p){return !Number(p.draftRank);}))rankClass(list);if(!g.draftClassSize)g.draftClassSize=list.length;if(!g.draftClassStrength){var top=list.slice().sort(function(a,b){return a.draftRank-b.draftRank;}).slice(0,10),avg=top.reduce(function(n,p){return n+(Number(p.projection)||0);},0)/Math.max(1,top.length);g.draftClassStrength=avg>=91?'ELITE CLASS':avg>=88.5?'STRONG CLASS':avg>=86.5?'ABOVE AVERAGE':avg>=84.5?'AVERAGE CLASS':'THIN CLASS';}g.draftModelVersion=Math.max(3,Number(g.draftModelVersion)||0);return {size:g.draftClassSize,strength:g.draftClassStrength};};

/* ---------- order + lottery ---------- */
function rows(g){return X.teams.map(function(t){return {id:t.id,name:t.name,rec:X.ensureStandingsRecord(g.standings&&g.standings[t.id])};});}
function worstFirst(list){return X.standingsSort(list).reverse();}
function playoffInfo(g){var p=g.playoff||{},field=(p.field||[]).slice(),rr=p.roundResults||[],champ=p.champion||((rr[3]||[])[0]&&rr[3][0].winner)||(p.complete?p.winner:null),elim={};field.forEach(function(id){if(id===champ){elim[id]=4;return;}var lost=-1,won=0;for(var r=0;r<4;r++)(rr[r]||[]).forEach(function(m){if(m.a===id||m.b===id){if(m.winner===id)won=r+1;else lost=r;}});elim[id]=lost>=0?lost:won;});return {field:field,champ:champ,elim:elim};}
function baseOrder(g){var all=rows(g),info=playoffInfo(g),field=info.field;if(field.length<16){var best=X.standingsSort(all).slice(0,16).map(function(x){return x.id;});field=best;info.elim={};}var non=worstFirst(all.filter(function(x){return field.indexOf(x.id)<0;})).map(function(x){return x.id;}),po=all.filter(function(x){return field.indexOf(x.id)>=0;}),bucket={};po.forEach(function(x){var e=info.elim[x.id]||0;if(e===1)e=0;(bucket[e]=bucket[e]||[]).push(x);});var dw={},divs={};all.forEach(function(x){var d=X.team(x.id).division;(divs[d]=divs[d]||[]).push(x);});Object.keys(divs).forEach(function(d){var top=X.standingsSort(divs[d])[0];if(top)dw[top.id]=1;});var pl=[];[0,2,3,4].forEach(function(e){if(!bucket[e])return;if(e===0){var a=bucket[e].filter(function(x){return !dw[x.id];}),b=bucket[e].filter(function(x){return dw[x.id];});pl=pl.concat(worstFirst(a).map(function(x){return x.id;}),worstFirst(b).map(function(x){return x.id;}));}else pl=pl.concat(worstFirst(bucket[e]).map(function(x){return x.id;}));});/* patch13 D1: NHL rule, picks 17-28 = R1+R2 losers by points, division winners last */return {non:non,playoff:pl,champ:info.champ};}
function runLottery(g,year,non){var r=rng(seedOf(g)+'|lottery|'+year),hist=g.lotteryHistory||[],recent={};hist.filter(function(h){return h.year>=year-5&&h.year<year;}).forEach(function(h){(h.winners||[]).forEach(function(w){recent[w]=(recent[w]||0)+1;});});var winners=[],draws=[];
 for(var d=1;d<=2;d++){var pool=non.map(function(id,i){return [id,winners.indexOf(id)<0&&(recent[id]||0)<2?ODDS[i]:0];}).filter(function(x){return x[1]>0;}),w=pickW(r,pool);winners.push(w);draws.push({draw:d,team:w,preRank:non.indexOf(w)+1,odds:ODDS[non.indexOf(w)]});}
 var final=new Array(16);draws.forEach(function(x){var target=Math.max(x.draw,x.preRank-10);if(x.preRank<target)target=x.preRank;while(final[target-1])target++;final[target-1]=x.team;x.pick=target;});var rest=non.filter(function(id){return winners.indexOf(id)<0;}),k=0;for(var i=0;i<16;i++)if(!final[i])final[i]=rest[k++];
 return {year:year,pre:non.slice(),odds:ODDS.slice(),draws:draws,final:final};}
function ensureOrder(g){var off=g.offseason;if(!off)return null;var year=draftYearOf(g);if(off.draftOrder&&off.draftOrder.year===year)return off.draftOrder;var b=baseOrder(g),lot=b.non.length===16?runLottery(g,year,b.non):null,order=(lot?lot.final:b.non).concat(b.playoff),slots={};order.forEach(function(id,i){slots[id]=i+1;});off.draftOrder={year:year,order:order,slots:slots,lottery:lot,champ:b.champ};if(lot){g.lotteryHistory=(g.lotteryHistory||[]).filter(function(h){return h.year!==year;});g.lotteryHistory.push({year:year,winners:lot.draws.filter(function(x){return x.pick<x.preRank;}).map(function(x){return x.team;})});}return off.draftOrder;}
D.ensureOrder=ensureOrder;D._runLottery=runLottery;
D.draftSlotForTeam=function(g,id){var o=g.offseason&&g.offseason.draftOrder;if(o&&o.year===draftYearOf(g)&&o.slots[id])return o.slots[id];var b=baseOrder(g),order=b.non.concat(b.playoff),i=order.indexOf(id);return i<0?32:i+1;};
D.draftPickOverall=function(g,pick){var st=g.offseason&&g.offseason.liveDraft,key=X.pickKey(pick);if(st&&st.v===2&&Number(pick.year)===st.year){var row=st.order.find(function(x){return x.pickKey===key;});if(row)return row.overall;}return (Math.max(1,Number(pick.round)||1)-1)*32+D.draftSlotForTeam(g,pick.origin||pick.team);};
D.offseasonPlacement=function(g){var res=O.offseasonPlacement(g);if(g.offseason&&g.offseason.draftOrder)res.lottery=false;return res;};

/* ---------- live draft ---------- */
D.initializeDraftOrder=function(g){var off=g.offseason,year=draftYearOf(g);if(off.liveDraft&&off.liveDraft.v===2&&off.liveDraft.year===year)return off.liveDraft;var ord=ensureOrder(g),assets={};teamIds().forEach(function(id){X.clubPicks(g,id).filter(function(p){return Number(p.year)===year;}).forEach(function(p){assets[(p.origin||p.team)+'|'+p.round]={owner:id,pick:p};});});var order=[],overall=0;
 for(var round=1;round<=7;round++)ord.order.forEach(function(origin,i){var a=assets[origin+'|'+round];if(a&&a.pick.forfeited)return;if(!a){var pk={id:origin+'-'+year+'-'+round,origin:origin,team:origin,year:year,round:round};X.clubPicks(g,origin).push(pk);a={owner:origin,pick:pk};}overall++;order.push({round:round,slot:i+1,overall:overall,origin:origin,owner:a.owner,pickKey:X.pickKey(a.pick)});});
 off.liveDraft={v:2,year:year,order:order,cursor:0,onClockKey:null,pendingTradeOffer:null,offerChecked:null};off.draftLog=[];return off.liveDraft;};
function live(g){return D.initializeDraftOrder(g);}
function syncClock(g){var st=live(g),row=st.order[st.cursor]||null;if(!row){st.onClockKey=null;return null;}if(row.owner===g.team){if(!X.findDraftAsset(g,g.team,row.pickKey)){g.userPicks=g.userPicks||[];g.userPicks.push({id:row.pickKey,origin:row.origin,team:g.team,year:st.year,round:row.round});}st.onClockKey=row.pickKey;if(st.offerChecked!==row.pickKey){st.offerChecked=row.pickKey;try{X.draftTradeOfferForUser(g,st,row);}catch(e){st.pendingTradeOffer=null;}}}else{st.onClockKey=null;st.pendingTradeOffer=null;}return row;}
function needBonus(g,id,pos){var c=club(g,id)||{},all=(c.roster||[]).concat(c.orgProspects||[],c.reserveRoster||[]),n=all.filter(function(p){return pos==='G'?p.pos==='G':pos==='D'?p.pos==='D':p.pos!=='G'&&p.pos!=='D';}).length;if(pos==='G')return n<3?0.8:n>5?-1:0;if(pos==='D')return n<9?0.6:n>13?-0.5:0;return n<15?0.5:0;}
function cpuScore(g,id,p,row){var r=rng(seedOf(g)+'|cpu|'+row.overall+'|'+id+'|'+p.id),sd=row.round<=2?1.1:2.2,s=p.projection+needBonus(g,id,p.pos)+gauss(r)*sd;if(p.pos==='G'&&row.round===1)s-=1.5;return s;}
function cpuChoose(g,row){var best=null,bs=-1e9;(g.prospects||[]).forEach(function(p){var s=cpuScore(g,row.owner,p,row);if(s>bs){bs=s;best=p;}});return best;}
function userChoose(g){var wl=g.scoutWatchlist||[],best=null,bs=-1e9;(g.prospects||[]).forEach(function(p){var r=p.scoutReport,est=r?(r.low+r.high)/2:p.projection;var s=est+needBonus(g,g.team,p.pos)+(wl.indexOf(p.id)>=0?1.5:0);if(s>bs){bs=s;best=p;}});return best;}
D.aiDraftPickScore=function(g,id,p){var st=g.offseason&&g.offseason.liveDraft,row=st&&st.order[st.cursor]||{overall:1,round:1};return cpuScore(g,id,p,row);};
function rightsYears(p,age){var t=leagueType(p);if(t==='CHL')return 2;if(age>=20&&t!=='NCAA')return 2;return 4;}
function initRights(g,p,row,ownerId,year){var age=ageAt(p.ctfoDob,iso(year,9,15))||p.age;p.club=ownerId;p.drafted=true;p.draftYear=year;p.draftRound=row.round;p.draftOverall=row.overall;p.pickTeam=row.origin;p.unsigned=true;p.years=0;p.salary=0;p.capHit=0;p.contractTimeline=[];p.contractType='';p.reserveList=true;p.contractExpired=false;
 p.ctfoDraft={year:year,round:row.round,overall:row.overall,club:ownerId,origin:row.origin,expires:year+rightsYears(p,age),status:'unsigned',declined:null};p.rosterStatus='Unsigned draft rights · '+(p.amateurTeam||'amateur')+' ('+(p.league||'')+')';p.etaYear=D.estimateNhlEta(p,year);p.developmentRoute=leagueType(p)==='CHL'?'Returns to CHL':leagueType(p)==='EURO'||/EURO/.test(leagueType(p))?'Stays in Europe':'College route';}
function elcTerms(g,p,year){var age=ageAt(p.ctfoDob,iso(year,9,15))||p.age,len=age<=21?3:age<=23?2:1,min=X.leagueMinFor?X.leagueMinFor(year):Math.max(775000,900000+(year-2027)*50000),max=min+175000,o=(p.ctfoDraft&&p.ctfoDraft.overall)||224,frac=o<=10?1:o<=32?0.85+0.15*(32-o)/22:o<=64?0.45:o<=96?0.3:0.12,aav=Math.round((min+frac*(max-min))/2500)*2500;return {len:len,aav:aav,age:age,max:max,min:min};}
D.elcTerms=elcTerms;
function signElc(g,p,ownerId,year,quiet){var c=club(g,ownerId);if(typeof X.ahlContractCount==='function'&&c){try{if(X.ahlContractCount(c)>=50)return 'limit';}catch(e){}}var t=elcTerms(g,p,year);p.unsigned=false;p.years=t.len;p.term=t.len;p.salary=t.aav;p.capHit=t.aav;p.contractTimeline=Array(t.len).fill(t.aav);p.contractType='Entry-level';p.contractSource='Entry-level contract · '+t.len+' yr · AAV '+money(t.aav)+' (ELC max '+money(t.max)+')';p.elc={signedYear:year,ageAtSigning:t.age,slidesLeft:t.age<=18?2:t.age===19?1:0,gpBase:Number(p.games)||0};p.contractExpired=false;if(p.ctfoDraft)p.ctfoDraft.status='signed';
 var junior=t.age<20&&(leagueType(p)==='CHL'||p.ovr<70);if(!junior&&c&&(c.orgProspects||[]).indexOf(p)>=0){c.orgProspects.splice(c.orgProspects.indexOf(p),1);c.reserveRoster=c.reserveRoster||[];c.reserveRoster.push(p);p.level='Minor league';p.rosterStatus='Signed ELC · AHL affiliate';}else p.rosterStatus='Signed ELC · '+(leagueType(p)==='CHL'?'returned to '+p.amateurTeam+' (CHL rule: AHL at 20)':'loaned to '+(p.amateurTeam||'junior club'));return 'signed';}
function cpuRightsDecision(g,p,row,year){var r=rng(seedOf(g)+'|cpuelc|'+p.id),t=leagueType(p);var chance=t==='CHL'?(row.overall<=20?0.6:row.overall<=64?0.25:0.05):t==='NCAA'||t==='NCAA_BOUND'?0:(row.overall<=15?0.35:0.04);if(r()<chance)signElc(g,p,row.owner,year,true);}
function makeSelection(g,row,p,how){var st=live(g),year=st.year,ownerId=row.owner,c=club(g,ownerId);g.prospects=(g.prospects||[]).filter(function(x){return x.id!==p.id;});initRights(g,p,row,ownerId,year);c.orgProspects=c.orgProspects||[];c.orgProspects.push(p);var list=X.clubPicks(g,ownerId),i=list.findIndex(function(x){return X.pickKey(x)===row.pickKey;});if(i>=0)list.splice(i,1);row.done=true;row.playerId=p.id;row.playerName=p.name;row.pos=p.pos;
 g.offseason.draftLog=g.offseason.draftLog||[];g.offseason.draftLog.push({overall:row.overall,round:row.round,team:ownerId,teamName:nm(ownerId),playerName:p.name,pos:p.pos,league:p.league,rank:p.draftRank,auto:how});
 if(ownerId===g.team){g.offseason.draftRights=g.offseason.draftRights||[];g.offseason.draftRights.push({playerId:p.id,overall:row.overall,round:row.round,status:'rights',autoSimulated:how==='auto'});g.history.push({year:X.seasonLabel(g),text:nm(g.team)+' select '+p.name+' ('+p.pos+', '+(p.amateurTeam||p.league)+') at #'+row.overall+'.',tag:'NHL DRAFT'});}else if(window.CTFODraftShow&&CTFODraftShow.cpuDecide)CTFODraftShow.cpuDecide(g,p,row,year);else cpuRightsDecision(g,p,row,year);
 st.cursor++;st.onClockKey=null;st.pendingTradeOffer=null;/* patch13 show */try{if(window.CTFODraftShow&&CTFODraftShow.picked)CTFODraftShow.picked(g,row,p,how);}catch(e){console.error('draft show',e);}}
function completeDraft(g){var st=live(g),off=g.offseason;if(st.completed)return;st.completed=true;g.drafted=true;teamIds().forEach(function(id){var l=X.clubPicks(g,id);for(var i=l.length-1;i>=0;i--)if(Number(l[i].year)===st.year)l.splice(i,1);});off.phase='signings';off.draftRightsReviewed=false;if(X.v4fixOffseasonTrades){try{X.v4fixOffseasonTrades(g,'draft');}catch(e){console.error('v4fix draft trades',e);}}g.history.push({year:X.seasonLabel(g),text:nm(g.team)+' completes the '+st.year+' NHL Draft. Draft rights are ready for signing decisions.',tag:'NHL DRAFT'});}
D.completeDraft=completeDraft;
function cpuStep(g){var row=syncClock(g);if(!row){completeDraft(g);return null;}if(row.owner===g.team)return row;var p=cpuChoose(g,row);if(!p){completeDraft(g);return null;}makeSelection(g,row,p,'cpu');row=syncClock(g);if(!row)completeDraft(g);return row;}
D.advanceDraftOnePick=function(g){if(!g.offseason||g.offseason.phase!=='draft')return null;return cpuStep(g);};
D.advanceDraftToUserPick=function(g){var row;for(var n=0;n<300;n++){row=cpuStep(g);if(!row||row.owner===g.team)break;}return row;};
D.simAll=function(g){for(var n=0;n<300;n++){var row=syncClock(g);if(!row)break;var p=row.owner===g.team?userChoose(g):cpuChoose(g,row);if(!p)break;makeSelection(g,row,p,row.owner===g.team?'auto':'cpu');}completeDraft(g);};
function ui(section,msg,bad){var cur=X.cur();cur.page='offseason';cur.offseasonSection=section;X.persist();X.renderOffice();if(msg)X.setNotice(msg,bad);}
D.finishDraft=function(g){if(!g||!g.offseason||g.offseason.phase!=='draft')return;D.simAll(g);ui('draft','Draft complete. Your remaining picks used your auto-pick board (scout reports, team need, watchlist). Review draft rights next.');};
D.draftBest=function(g,selectedId){if(!g.offseason||g.offseason.phase!=='draft')return;var row=syncClock(g);if(!row||row.owner!==g.team)return X.setNotice('Your club is not on the clock.',true);var p=(g.prospects||[]).find(function(x){return x.id===selectedId;})||userChoose(g);if(!p)return;makeSelection(g,row,p,'manual');g.offseason.playerCall={playerId:p.id,overall:row.overall,round:row.round,phase:'ringing'};X.persist();X.renderOffice();X.setNotice(nm(g.team)+' select '+p.name+' at #'+row.overall+'.');};
D.draftProspect=function(g,p){var row=syncClock(g);if(row&&p)makeSelection(g,row,p,'manual');};
D.applyAIDraftPlayerChoice=function(g,p,clubId,year){return p&&p.unsigned?'rights':'signed';};
D.acceptDraftTrade=function(g){var st=live(g),offer=st.pendingTradeOffer,row=st.order[st.cursor];if(!offer||!row)return;X.moveDraftPickAsset(g,offer.currentKey,g.team,offer.buyer);X.moveDraftPickAsset(g,offer.laterKey,offer.buyer,g.team);if(offer.extraKey)X.moveDraftPickAsset(g,offer.extraKey,offer.buyer,g.team);g.history.push({year:X.seasonLabel(g),text:nm(g.team)+' trade pick #'+row.overall+' to '+nm(offer.buyer)+' for pick #'+st.order[offer.laterRowIndex].overall+(offer.extraKey?' and a future pick':'')+'.',tag:'DRAFT TRADE'});st.pendingTradeOffer=null;st.offerChecked=null;cpuStep(g);ui('draft','Trade accepted. '+nm(offer.buyer)+' moved up.');};

/* ---------- rights screen + ELC offers ---------- */
function myRights(g,year){return (g.orgProspects||[]).concat(g.reserveRoster||[]).filter(function(p){return p.ctfoDraft&&(p.ctfoDraft.status==='unsigned'||p.ctfoDraft.year===year);});}
function acceptChance(p,year){var a=acceptChance0(p,year);return window.CTFODraftShow&&CTFODraftShow.adjustAccept?CTFODraftShow.adjustAccept(p,year,a):a;}
function acceptChance0(p,year){var t=leagueType(p),held=year-p.ctfoDraft.year;if(t==='CHL')return 0.92;if(t==='NCAA')return [0.15,0.35,0.55,0.85][Math.min(3,held)];if(t==='NCAA_BOUND')return held?0.4:0.25;return 0.7;}
D.offerElc=function(g,id){var p=myRights(g,draftYearOf(g)).find(function(x){return x.id===id;}),year=draftYearOf(g);if(!p||!p.unsigned)return;if(p.ctfoDraft.declined===year)return X.setNotice(p.name+' already turned down an entry-level deal this summer.',true);var r=rng(seedOf(g)+'|elc|'+p.id+'|'+year);if(r()>acceptChance(p,year)){p.ctfoDraft.declined=year;X.persist();X.renderOffice();return X.setNotice(p.name+' wants to stay with '+(p.amateurTeam||'his club')+' this year. You keep his rights until June '+p.ctfoDraft.expires+'.');}var res=signElc(g,p,g.team,year);X.persist();X.renderOffice();X.setNotice(res==='limit'?'You are at the 50-contract limit.':p.name+' signed: '+p.contractSource+'.',res==='limit');};
D.resolveDraftProspect=function(g,id){D.offerElc(g,id);};
D.renderDraftSigning=function(g){var year=draftYearOf(g),list=myRights(g,year).sort(function(a,b){return (a.ctfoDraft.overall||999)-(b.ctfoDraft.overall||999);}),esc=X.esc;
 var cards=list.map(function(p){var t=elcTerms(g,p,year),d=p.ctfoDraft,signed=!p.unsigned,final=d.expires===year+1;return '<article class="fo-panel ctfo-right"><div><p class="section-kicker">'+(d.year===year?'#'+d.overall+' · ROUND '+d.round:'DRAFTED '+d.year+' · #'+d.overall)+'</p><h3>'+esc(p.name)+' <small>'+esc(p.pos)+' · AGE '+p.age+'</small></h3><p>'+esc((p.amateurTeam||'')+' · '+(p.league||''))+'</p><p class="ctfo-small">'+(signed?esc(p.contractSource)+'<br>'+esc(p.rosterStatus):'Rights held until June 1, '+d.expires+(final?' · <b>final signing window</b>':'')+'<br>ELC if signed now: '+t.len+' yr × '+money(t.aav)+(d.declined===year?'<br>Declined an ELC this summer':''))+'</p>'+(window.CTFODraftShow&&CTFODraftShow.rightsNote?CTFODraftShow.rightsNote(p,year):'')+'</div>'+(signed?'<span class="small-badge">SIGNED</span>':'<button class="button button-gold" data-action="ctfo-elc" data-player="'+esc(p.id)+'" '+(d.declined===year?'disabled':'')+'>Offer entry-level contract</button>')+'</article>';}).join('')||'<p class="panel-subtitle">You hold no unsigned draft rights.</p>';
 X.$('office-content').innerHTML='<section class="fo-panel ctfo-rights-head"><p class="section-kicker">'+year+' NHL DRAFT · DRAFT RIGHTS</p><h2>Draft rights &amp; entry-level contracts</h2><p>Draftees start as unsigned rights on your reserve list (they do not count toward the 50-contract limit). CHL rights last 2 years, college and European rights 4 years. ELC length follows age at signing (18-21: 3 years, 22-23: 2, 24+: 1); salary is capped at the league minimum + $175K. Signed teenagers from the CHL return to junior until 20.</p></section><div class="ctfo-rights-grid">'+cards+'</div><div class="draft-night-actions"><button class="button button-gold" data-action="continue-to-free-agency">Continue to Free Agency →</button></div>';};

/* ---------- ETA / stage ---------- */
D.estimateNhlEta=function(p,baseYear){var ovr=Number(p.ovr)||50,pot=Number(p.potential)||ovr,age=Number(p.age)||19;if(ovr>=READY)return baseYear;if(pot<READY-2)return baseYear+8;var rate=age<=20?3.5:age<=22?2.8:age<=24?1.8:1,yrs=Math.ceil((READY-ovr)/rate);if(pot<READY+1)yrs+=2;if(age<=18)yrs=Math.max(yrs,2);return baseYear+cl(yrs,0,8);};
D.prospectStage=function(p,cy){var eta=D.estimateNhlEta(p,cy);if(eta<=cy)return 'NHL-ready';if(p.ctfoDraft&&p.unsigned)return 'Unsigned rights · '+(p.league||'amateur');if(p.ctfoDraft&&(p.age<20)&&leagueType(p)==='CHL')return 'Junior · '+(p.league||'CHL');if((Number(p.age)||20)<=19)return 'Development camp';return 'Development system';};
D.prospectRoute=function(p){var t=leagueType(p);if(!p.leagueCode)return O.prospectRoute(p);return t==='CHL'?p.league+' junior route, AHL eligible at 20':t==='NCAA'?'NCAA college route':t==='NCAA_BOUND'?p.league+' to NCAA route':'European club route ('+p.league+')';};

/* ---------- draft-night UI ---------- */
function lotteryPanel(g,compact){var o=g.offseason&&g.offseason.draftOrder,l=o&&o.lottery,esc=X.esc;if(!l)return '';var moved=l.final.map(function(id,i){var pre=l.pre.indexOf(id)+1,mv=pre-(i+1);return '<tr class="'+(mv>0?'ctfo-up':'')+(id===g.team?' ctfo-mine':'')+'" style="animation-delay:'+((15-i)*0.12).toFixed(2)+'s"><td>'+(i+1)+'</td><td>'+esc(nm(id))+'</td><td>'+pre+'</td><td>'+l.odds[pre-1]+'%</td><td>'+(mv>0?'▲'+mv:mv<0?'▼'+(-mv):'—')+'</td></tr>';}).join('');
 var summary=l.draws.map(function(d){return 'Draw '+d.draw+': '+esc(nm(d.team))+' (pre-lottery #'+d.preRank+', '+d.odds+'%) → pick '+d.pick;}).join(' · ');
 return '<details class="fo-panel ctfo-lottery" '+(compact?'':'open')+'><summary><span class="section-kicker">'+l.year+' NHL DRAFT LOTTERY · 2 DRAWS · MAX JUMP 10 SPOTS</span><b>'+summary+'</b></summary><table><thead><tr><th>Pick</th><th>Club</th><th>Pre-lottery</th><th>Odds (#1)</th><th>Move</th></tr></thead><tbody>'+moved+'</tbody></table><small>Picks 17-32: playoff clubs by round eliminated, then fewest points. Stanley Cup champion '+(o.champ?esc(nm(o.champ))+' ':'')+'picks 32nd.</small></details>';}
D.lotteryPanel=lotteryPanel;
function board(g,st){var esc=X.esc,cur=st.order[st.cursor]||null,round=D._round||(cur?cur.round:7),list=st.order.filter(function(r){return r.round===round;}),tabs=[1,2,3,4,5,6,7].map(function(n){return '<button type="button" class="scout-filter '+(n===round?'active':'')+'" data-action="ctfo-round" data-round="'+n+'">R'+n+'</button>';}).join('');
 return '<section class="draft-room-board panel"><header class="draft-room-head"><div><p class="section-kicker">'+st.year+' NHL DRAFT · ROUND '+round+'</p><h2>Live draft board</h2><div class="scout-filters">'+tabs+'</div></div><span class="small-badge">PICK '+(cur?cur.overall:'—')+' OF '+st.order.length+'</span></header><div class="draft-room-picks">'+list.map(function(r){var up=cur&&cur.overall===r.overall,label=r.done?esc(r.playerName)+' · '+esc(r.pos):up?'ON THE CLOCK':'WAITING';return '<article class="draft-room-pick '+(up?'on-clock':r.done?'picked':'')+'"><span class="draft-room-overall">'+String(r.overall).padStart(2,'0')+'</span><span class="draft-room-crest">'+X.officeMark(r.owner,'standings-crest')+'</span><span class="draft-room-club"><b>'+esc(nm(r.owner))+'</b><small>'+(r.owner!==r.origin?'From '+esc(nm(r.origin)):'Round '+r.round+' · Pick '+r.slot)+'</small></span><span class="draft-room-status">'+label+'</span></article>';}).join('')+'</div></section>';}
D.renderDraftNight=function(g){var off=g.offseason;if(off.playerCall){X.renderDraftPlayerCall(g);return;}if(off.phase==='free-agency'){X.renderFreeAgency(g);return;}var st=live(g),clock=syncClock(g),esc=X.esc;if(!clock&&!st.completed&&off.phase==='draft')completeDraft(g);X.renderProspects(g,true);var isUser=clock&&clock.owner===g.team,mine=st.order.filter(function(r){return !r.done&&r.owner===g.team;}),log=(off.draftLog||[]).slice(-4).reverse(),src=(g.prospects[0]&&g.prospects[0].dataSource)||'Draft class',
  ticker=log.length?log.map(function(x){return '<div><span>#'+String(x.overall).padStart(2,'0')+'</span><b>'+esc(x.teamName)+'</b><small>'+esc(x.playerName)+' · '+esc(x.pos)+'</small></div>';}).join(''):'<div><span>LIVE</span><b>Commissioner at the podium</b><small>The draft board is open</small></div>';
 var html='<section class="draft-night-stage"><div class="draft-night-lights" aria-hidden="true"><i></i><i></i><i></i></div><div class="draft-night-brand"><span>THE NHL DRAFT</span><b>'+st.year+'</b></div><div class="draft-night-main"><p class="section-kicker">'+(clock?esc(nm(clock.owner).toUpperCase())+' IS ON THE CLOCK':'DRAFT COMPLETE')+'</p><h2>'+(isUser?'Your table. Your pick.':clock?'The board is moving.':'Draft night is complete.')+'</h2><p>'+(isUser?'You are up at pick #'+clock.overall+'. Choose a prospect below.':clock?'Your picks left: '+(mine.length?mine.map(function(r){return '#'+r.overall;}).join(', '):'none')+'.':'All 7 rounds are recorded. Continue to draft rights.')+'</p><div class="draft-night-pick"><span>'+(isUser?'YOUR SELECTION':'CURRENT SELECTION')+'</span><strong>'+(clock?'#'+clock.overall:'—')+'</strong><small>'+(clock?'ROUND '+clock.round+' · '+esc(nm(clock.origin))+' PICK':'NO PICKS REMAINING')+'</small></div></div><div class="draft-night-podium"><span class="podium-light"></span><span class="podium-mark">'+esc(clock?clock.owner:g.team)+'</span><b>GENERAL<br>MANAGER</b><small>'+(isUser?'YOUR SEAT':'ON THE CLOCK')+'</small></div><div class="draft-night-ticker">'+ticker+'</div><p class="draft-night-note">'+esc(src)+' · NHL order with lottery · 7 rounds.</p><div class="draft-night-actions">'+
  (clock?'<button class="button button-quiet" data-action="simulate-next-pick" '+(isUser?'disabled':'')+'>'+(isUser?'Your club is on the clock':'Make next pick →')+'</button><button class="button button-quiet" data-action="ctfo-sim-to-mine" '+(isUser?'disabled':'')+'>'+(mine.length?'Sim to my next pick →':'Sim to end of draft →')+'</button><button class="button button-gold" data-action="finish-draft">Auto-draft the rest (incl. my picks) →</button>':'<button class="button button-gold" data-action="ctfo-open-rights">Go to Draft Rights →</button>')+'</div></section>';
 X.$('office-content').insertAdjacentHTML('afterbegin',html);var stage=X.$('office-content').querySelector('.draft-night-stage'),offer=st.pendingTradeOffer;
 if(offer&&isUser){var sweet=offer.extraKey?X.findDraftAsset(g,offer.buyer,offer.extraKey):null;stage.insertAdjacentHTML('afterend','<section class="fo-panel draft-live-trade"><p class="section-kicker">TRADE-DOWN OFFER · PICK #'+clock.overall+'</p><h3>'+esc(nm(offer.buyer))+' wants to move up</h3><p>They offer pick #'+st.order[offer.laterRowIndex].overall+(sweet?' plus a future Round '+sweet.round+' pick':'')+' for your current selection.</p><div class="draft-trade-actions"><button class="button button-gold" data-action="accept-draft-trade">Accept trade →</button><button class="button button-quiet" data-action="decline-draft-trade">Decline and make your pick</button></div></section>');}
 stage.insertAdjacentHTML('afterend',board(g,st));stage.insertAdjacentHTML('afterend',lotteryPanel(g,st.cursor>0));fixLabels(g);};
D.draftRoomBoard=function(g,st){return board(g,st);};
function bio(p){var esc=X.esc;if(!p||!p.leagueCode&&!p.real)return '';var s=p.stats||{},line=p.pos==='G'?(s.gp?s.gp+' GP · '+s.svp+' SV% · '+s.gaa+' GAA':''):(s.gp?s.gp+' GP · '+s.g+' G · '+s.a+' A · '+s.pts+' PTS':''),ft=p.heightCm?Math.floor(p.heightCm/2.54/12)+'\''+Math.round(p.heightCm/2.54%12)+'"':'';
 return '<div class="scout-comp ctfo-bio"><span>'+(p.real?'REAL PROSPECT':'PROSPECT BIO')+' · '+esc(p.nationality||'')+'</span><strong>'+esc((p.amateurTeam||'')+' · '+(p.league||''))+'</strong><small>Born '+esc(p.ctfoDob||'?')+' · '+ft+' / '+(p.heightCm||'?')+' cm · '+(p.weightKg?Math.round(p.weightKg*2.2046)+' lb':'')+' · '+(p.pos==='G'?'Catches ':'Shoots ')+esc(p.shoots||'?')+'<br>'+esc((s.season||'')+' '+line)+'<br>'+esc(p.dataSource||'')+'</small></div>';}
function fixLabels(g){var root=X.$('office-content');if(!root)return;root.querySelectorAll('button[data-action="finish-draft"]').forEach(function(b){b.textContent='Auto-draft the rest (incl. my picks) →';});var cur=X.cur(),p=(g.prospects||[]).find(function(x){return x.id===cur.scoutingFocus;}),top=root.querySelector('.scout-profile-top');if(p&&top&&!root.querySelector('.ctfo-bio'))top.insertAdjacentHTML('afterend',bio(p));root.querySelectorAll('.scout-comp small').forEach(function(s){if(/generated class/.test(s.textContent))s.textContent=s.textContent.replace('in this generated class','in this class');});}
D.renderProspects=function(g,mode){O.renderProspects(g,mode);fixLabels(g);};
D.renderDraftPlayerCall=function(g){O.renderDraftPlayerCall(g);var m=X.$('office-content')&&X.$('office-content').querySelector('.draft-call-meta span');if(m)m.textContent=draftYearOf(g)+' NHL DRAFT';};
D.renderOffseasonEntry=function(g){if(!g.offseason)return O.renderOffseasonEntry(g);ensureOrder(g);O.renderOffseasonEntry(g);var c=X.$('office-content'),call=c&&c.querySelector('.offseason-draft-callout');if(call){var sm=call.querySelector('small');if(sm&&g.offseason.draftOrder&&g.offseason.draftOrder.lottery)sm.textContent='After the '+draftYearOf(g)+' draft lottery. '+sm.textContent.replace(/^Draft position follows the club that originally owned this pick\.\s*/,'');call.insertAdjacentHTML('afterend',lotteryPanel(g,false));}};
D.beginOffseason=function(g){O.beginOffseason(g);try{seasonEndRules(g);}catch(e){console.error('draft rules',e);}(g.history||[]).forEach(function(h){if(/^Boston enters the offseason/.test(h.text||''))h.text=h.text.replace('Boston',nm(g.team)).replace('Providence','the AHL affiliate');});try{ensureOrder(g);}catch(e){console.error('draft order',e);}};
D.advanceSeason=function(g){var s0=g&&g.season,r=O.advanceSeason.apply(this,arguments);if(g&&g.season!==s0){try{window.CTFODraftShow&&CTFODraftShow.summerTick&&CTFODraftShow.summerTick(g);}catch(e){console.error('draft show summer',e);}}try{var d=iso(startYear(g)+Number(g.season||1)-1,10,1);teamIds().forEach(function(id){var c=club(g,id);if(!c)return;(c.roster||[]).concat(c.orgProspects||[],c.reserveRoster||[]).forEach(function(p){if(p.ctfoDob){var a=ageAt(p.ctfoDob,d);if(a)p.age=a;}});});}catch(e){console.error('draft ages',e);}return r;};
D.progressPlayerOffseason=function(p,clubId,g){var r=O.progressPlayerOffseason.apply(this,arguments);try{if(p&&p.ctfoDob&&g){var y=g.offseason&&g.offseason.year?Number(g.offseason.year):startYear(g)+Number(g.season||1)-1,a=ageAt(p.ctfoDob,iso(y,10,1));if(a)p.age=a;}}catch(e){}return r;};
D.restoreRosterDepth=function(g,clubId,c){c=c||club(g,clubId);if(!c)return O.restoreRosterDepth.apply(this,arguments);var bad=function(p){return p.ctfoDraft&&(p.unsigned||(p.ovr<74&&(Number(p.age)||20)<20));},ho=(c.orgProspects||[]).filter(bad),hr=(c.reserveRoster||[]).filter(bad);if(c.orgProspects)c.orgProspects=c.orgProspects.filter(function(p){return !bad(p);});if(c.reserveRoster)c.reserveRoster=c.reserveRoster.filter(function(p){return !bad(p);});try{return O.restoreRosterDepth.apply(this,arguments);}finally{c.orgProspects=(c.orgProspects||[]).concat(ho);c.reserveRoster=(c.reserveRoster||[]).concat(hr);}};
D.promoteProspect=function(g,id){var p=(g.orgProspects||[]).concat(g.reserveRoster||[]).find(function(x){return x.id===id;});if(p&&p.ctfoDraft&&p.unsigned)return X.setNotice(p.name+' is unsigned draft rights. Offer him an entry-level contract in Draft Rights first.',true);return O.promoteProspect(g,id);};

/* patch13 draft rules */
function rerankInsert(list,p){var better=list.filter(function(x){return x!==p&&(Number(x.projection)||0)>(Number(p.projection)||0);}).length,rank=better+1;list.forEach(function(x){if(x!==p&&Number(x.draftRank)>=rank)x.draftRank=Number(x.draftRank)+1;});p.draftRank=rank;}
function lapseRights(g,year){var notes=[];teamIds().forEach(function(id){var c=club(g,id);if(!c)return;['orgProspects','reserveRoster'].forEach(function(k){var keep=[];(c[k]||[]).forEach(function(p){var d=p.ctfoDraft;if(!(d&&p.unsigned&&Number(d.expires)<=year)){keep.push(p);return;}
  var age=ageAt(p.ctfoDob,iso(year,9,15))||Number(p.age)||21,hist=(p.draftHistory||[]).concat([{year:d.year,overall:d.overall,club:d.club,lapsed:year}]);
  if(age<=20&&!p.reentered){p.draftHistory=hist;p.reentered=true;p.ctfoDraft=null;p.drafted=false;p.club=null;p.unsigned=false;p.reserveList=false;p.draftYear=year;p.draftRound=null;p.draftOverall=null;p.pickTeam=null;p.rosterStatus='Draft re-entry ('+year+')';p.dataSource=(p.dataSource||'')+' · re-entered after unsigned rights lapsed';g.prospects=g.prospects||[];if(g.prospects.indexOf(p)<0){g.prospects.push(p);rerankInsert(g.prospects,p);}
   if(id===g.team)notes.push(p.name+' re-enters the '+year+' draft');}
  else{if(id===g.team)notes.push(p.name+' becomes a free agent');}});c[k]=keep;});});
 if(notes.length)g.history.push({year:X.seasonLabel(g),text:nm(g.team)+' draft rights lapsed (unsigned by June 1, '+year+'): '+notes.join('; ')+'.',tag:'DRAFT RIGHTS'});return notes;}
function elcSeasonEnd(g,year){teamIds().forEach(function(id){var c=club(g,id);if(!c)return;var nhl=c.roster||[];nhl.concat(c.reserveRoster||[],c.orgProspects||[]).forEach(function(p){var e=p.elc;if(!e||p.unsigned||e.lastSeasonEnd===year||Number(e.signedYear)>=year)return;e.lastSeasonEnd=year;var onNhl=nhl.indexOf(p)>=0,gp=Math.max(0,Number(p.games)||0);e.gpBase=0;
  var aav=Number(p.salary)||Number(p.capHit)||0;
  if(Number(e.slidesLeft)>0&&gp<10){e.slidesLeft--;e.slid=(Number(e.slid)||0)+1;if(onNhl){p.years=Number(p.years)+1;p.term=Number(p.term||p.years);if(Array.isArray(p.contractTimeline))p.contractTimeline.push(aav);}p.contractSource=String(p.contractSource||'').replace(/ · slid \d+ yr$/,'')+' · slid '+e.slid+' yr';return;}
  if(onNhl)return;/* NHL-roster contracts burn in expireSeasonContracts */
  p.years=Math.max(0,Number(p.years)-1);if(Array.isArray(p.contractTimeline)&&p.contractTimeline.length)p.contractTimeline.shift();
  if(p.years<=0){var min=X.leagueMinFor?X.leagueMinFor(year):Math.max(775000,900000+(year-2027)*50000);p.years=2;p.term=2;p.salary=min;p.capHit=min;p.contractTimeline=[min,min];p.contractType='Two-way';p.elc=null;p.contractSource='Two-way re-sign after ELC · 2 yr · '+money(min);p.rosterStatus='Two-way contract · minor league';}});});}
function seasonEndRules(g){var year=draftYearOf(g);elcSeasonEnd(g,year);var n=lapseRights(g,year);if(n.length&&X.setNotice)try{X.setNotice('Draft rights lapsed: '+n.join('; ')+'.');}catch(e){}}
/* ---------- actions (capture phase, before the game's own click handler) ---------- */
function onClick(ev){var b=ev.target&&ev.target.closest&&ev.target.closest('[data-action]');if(!b||b.disabled)return;var a=b.dataset.action,cur=X.cur(),g=cur&&cur.game;if(!g||!g.offseason)return;var mine={'ctfo-sim-to-mine':1,'ctfo-round':1,'ctfo-open-rights':1,'ctfo-elc':1,'continue-after-player-call':1,'start-offseason-draft':1,'continue-to-draft':1,'simulate-next-pick':1};if(!mine[a])return;ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();var off=g.offseason;
 if(a==='start-offseason-draft'||a==='continue-to-draft'){off.phase='draft';if(X.aiDraftTradeWindow){try{X.aiDraftTradeWindow(g);}catch(e){console.error(e);}}live(g);D.advanceDraftOnePick(g);ui(off.phase==='draft'?'draft':'freeagency');return;}
 if(a==='simulate-next-pick'){D.advanceDraftOnePick(g);ui('draft');return;}
 if(a==='ctfo-sim-to-mine'){var row=D.advanceDraftToUserPick(g);ui('draft',row?'You are on the clock at #'+row.overall+'.':'The draft is complete.');return;}
 if(a==='ctfo-round'){D._round=Number(b.dataset.round)||null;ui('draft');return;}
 if(a==='ctfo-open-rights'){if(off.phase==='draft')completeDraft(g);ui('draft');return;}
 if(a==='ctfo-elc'){D.offerElc(g,b.dataset.player);return;}
 if(a==='continue-after-player-call'){off.playerCall=null;D._round=null;if(off.phase==='draft')D.advanceDraftOnePick(g);ui('draft');return;}}
D.install=function(deps){X=deps;O=deps.orig;D.X=deps;D.api={signElc:signElc,elcTerms:elcTerms,leagueType:leagueType,ageAt:ageAt,iso:iso,seedOf:seedOf,needBonus:needBonus,draftYearOf:draftYearOf,acceptChance:acceptChance0};document.addEventListener('click',onClick,true);if(!document.getElementById('ctfo-draft-css')){var s=document.createElement('style');s.id='ctfo-draft-css';s.textContent='.ctfo-lottery{margin:12px 0}.ctfo-lottery summary{cursor:pointer;display:flex;flex-direction:column;gap:4px}.ctfo-lottery table{width:100%;border-collapse:collapse;margin:8px 0;font-size:13px}.ctfo-lottery td,.ctfo-lottery th{padding:3px 8px;text-align:left;border-bottom:1px solid rgba(255,255,255,.08)}.ctfo-lottery tbody tr{animation:ctfoIn .5s both}.ctfo-lottery tr.ctfo-up{color:#f4c542;font-weight:700}.ctfo-lottery tr.ctfo-mine{outline:2px solid #f4c542}@keyframes ctfoIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}.ctfo-rights-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:12px;margin:12px 0}.ctfo-right{display:flex;flex-direction:column;justify-content:space-between;gap:8px}.ctfo-small{font-size:12px;opacity:.85}.ctfo-bio small{line-height:1.5}';document.head.appendChild(s);}
 var R={};['makeProspects','draftClassInfo','draftSlotForTeam','draftPickOverall','offseasonPlacement','initializeDraftOrder','advanceDraftOnePick','advanceDraftToUserPick','finishDraft','draftBest','draftProspect','aiDraftPickScore','applyAIDraftPlayerChoice','resolveDraftProspect','acceptDraftTrade','renderDraftNight','draftRoomBoard','renderDraftSigning','renderDraftPlayerCall','renderProspects','renderOffseasonEntry','estimateNhlEta','prospectStage','prospectRoute','beginOffseason','advanceSeason','progressPlayerOffseason','restoreRosterDepth','promoteProspect'].forEach(function(k){R[k]=D[k];});deps.rebind(R);};
})();
