/* Player overalls and potential labels supplied by the user from NHLRatings. */
window.NHL_RATINGS = {
  ANA: [
    'Mikael Granlund|C|87|Low','Troy Terry|RW|86|Med','Beckett Sennecke|RW|85|High','Jackson LaCombe|D|85|Med','Lukas Dostal|G|85|Med','Chris Kreider|LW|84|Med','Cutter Gauthier|LW|84|Med','Frank Vatrano|RW|84|Med','Leo Carlsson|C|84|Med','Petr Mrazek|G|84|Med','Ville Husso|G|84|Med','Nick Jensen|D|83|High','Alex Killorn|LW|82|High','Laurent Brossoit|G|82|High','Pavel Mintyukov|D|82|Med','Ryan Poehling|C|80|Med','A.J. Greer|LW|79|Med','Sam Colangelo|RW|79|Med','Noah Philp|C|78|Exact','Ian Moore|D|77|Med','Tristan Luneau|D|77|Med','Corey Schueneman|D|75|Exact','Drew Helleson|D|75|Med','James Hamblin|LW|75|Med','Jeff Malott|LW|75|Exact','Nathan Gaucher|C|75|Med','Tim Washe|C|75|Med','Tyson Hinds|D|75|Med','Anton Wahlberg|C|74|Med','Nikita Nesterenko|C|74|Med','Jett Woo|D|73|Med','Noah Warren|D|71|Med','Stian Solberg|D|70|Med','Judd Caulfield|RW|69|Med','Nico Myatovic|LW|69|Med'
  ],
  BOS: [
    'David Pastrnak|RW|95|Exact','Charlie McAvoy|D|89|Med','Hampus Lindholm|D|86|Med','JJ Peterka|RW|86|Med','Jeremy Swayman|G|85|Med','Nikita Zadorov|D|85|Med','Casey Mittelstadt|C|84|Low','Elias Lindholm|C|84|Med','Mason Lohrei|D|84|Med','Pavel Zacha|C|84|Low','Morgan Geekie|C|83|Med','Connor Clifton|D|82|Med','Fraser Minten|C|82|Med','Marat Khusnutdinov|C|82|Med','Mark Kastelic|C|81|Med','Michael Eyssimont|C|81|Med','Sean Kuraly|C|81|Med','Will Borgen|D|81|Med','Henri Jokiharju|D|80|Low','Matthew Poitras|C|80|High','Victor Soderstrom|D|80|Med','Jordan Harris|D|79|Med','Tanner Jeannot|LW|79|Med','Ivan Ivan|C|78|Low','Jonathan Aspirot|D|78|Med','Brian Halonen|LW|76|Med','James Hagens|C|76|Med','Brendan Gaunce|C|75|Med','Alex Steeves|C|74|Med','Maxence Guenette|D|73|Med','Kalle Vaisanen|LW|63|Med'
  ],
  BUF: [
    'Rasmus Dahlin|D|93|High','Tage Thompson|C|89|Med','Owen Power|D|86|Med','Josh Norris|C|85|Med','Ryan McLeod|C|84|Low','Ukko-Pekka Luukkonen|G|84|Med','Alex Lyon|G|83|High','Jason Zucker|LW|83|Med','Justin Danforth|RW|82|Med','Mattias Samuelsson|D|82|Med','Olen Zellweger|D|82|Med','Zach Benson|LW|82|Med','Jack Quinn|RW|81|Med','Peyton Krebs|C|81|Med','Tanner Pearson|LW|81|Low','Beck Malenstyn|LW|80|Med','Conor Timmins|D|80|Low','Jiri Kulich|C|80|Med','Sam Carrick|C|80|Low','Josh Doan|RW|79|Med','Logan Stanley|D|79|High','Trevor Kuntar|C|78|Med','Konsta Helenius|C|77|Med','Ryan Johnson|D|77|Med','Tyson Kozak|C|76|Med','Zach Metsa|D|76|High','Conor Sheary|LW|75|Exact','Dennis Gilbert|D|75|Med','Louis Crevier|D|75|Med','Radim Mrtka|D|70|Med','Vsevolod Komarov|D|69|Med','Jason Polin|RW|68|Med','Riley Fiddler-Schultz|C|68|Med'
  ],
  CGY: [
    'Dustin Wolf|G|87|Med','Jonathan Huberdeau|LW|86|Med','Jake Middleton|D|84|Low','Kevin Bahl|D|84|High','Matt Coronato|RW|84|Med','Maxim Tsyplakov|RW|84|','Mikael Backlund|C|84|Med','Ryan Strome|C|84|Med','Morgan Frost|C|83|Med','Yegor Sharangovich|C|83|Med','Connor Zary|C|82|Med','Simon Nemec|D|82|Med','Zach Whitecloud|D|82|Med','Jake Bean|D|81|Med','Joel Farabee|LW|81|Med','Martin Pospisil|C|80|Low','Adam Klapka|RW|79|Med','Brayden Pachal|D|78|Med','Joel Hanley|D|78|Low','Samuel Honzek|LW|78|Med','Yan Kuznetsov|D|77|Med','Zayne Parekh|D|77|Med','Matvei Gridin|RW|76|Med','Hunter Brzustewicz|D|75|Med','Michael Benning|D|75|Exact','Abram Wiebe|D|74|Med','Tyson Gross|C|74|Med','Sam Morton|C|73|Low','Devin Cooley|G|72|Med','Ben Jones|C|70|Med'
  ],
  CAR: [
    'Jaccob Slavin|D|90|Med','Sebastian Aho|C|90|Med','Nikolaj Ehlers|LW|88|Med','Seth Jarvis|C|88|Med','Andrei Svechnikov|RW|87|Med','Shayne Gostisbehere|D|87|Med','K’Andre Miller|D|86|Med','Logan Stankoven|C|85|Med','Pyotr Kochetkov|G|85|Med','Alexander Nikishin|D|84|Low','Taylor Hall|LW|84|Med','Jesperi Kotkaniemi|C|83|Low','Jordan Martinook|LW|83|Med','Jordan Staal|C|83|High','Sean Walker|D|83|Low','Eric Robinson|LW|82|Med','Jalen Chatfield|D|81|Med','Jackson Blake|RW|80|Med','William Carrier|LW|80|High','Mark Jankowski|C|79|Med','Nicolas Deslauriers|LW|78|Med','Mike Reilly|D|77|Med','Felix Unger Sorum|RW|72|Med','Kyle Masters|D|67|Med'
  ],
  CHI: [
    'Connor Bedard|C|88|Med','Bowen Byram|D|85|Med','Alex Vlasic|D|84|Med','Matt Grzelcyk|D|84|Med','Ryan Donato|C|84|Med','Teuvo Teravainen|C|84|Med','Spencer Knight|G|83|Med','Andrew Mangiapane|LW|82|Med','Arvid Soderblom|G|82|Med','Frank Nazar|C|82|Med','Ian Cole|D|82|High','Tyler Bertuzzi|LW|82|Med','Artyom Levshunov|D|81|Med','Jordan Greenway|LW|81|Med','Cole Smith|LW|80|Med','Anton Frondell|C|79|Med','Oliver Moore|C|79|Med','Ryan Greene|C|79|Med','Sam Rinzel|D|79|Med','Kevin Korchinski|D|78|Med','Nick Lardis|LW|78|Med','Dominic Toninato|C|77|Med','Ethan Del Mastro|D|77|Med','Brett Seney|LW|76|Exact','Sacha Boisvert|C|76|Med','Wyatt Kaiser|D|76|Med','Connor Mackey|D|75|Exact','Landon Slaggert|LW|75|Med','Dylan Anhorn|D|70|Med','Cavan Fitzgerald|D|68|Med'
  ],
  COL: [
    'Nathan MacKinnon|C|97|Exact','Cale Makar|D|95|Exact','Martin Necas|C|92|Med','Devon Toews|D|89|Med','Nazem Kadri|C|87|High','Brock Nelson|C|86|Low','Mackenzie Blackwood|G|86|Med','Artturi Lehkonen|LW|85|Med','Brent Burns|D|85|Med','Gabriel Landeskog|LW|85|Med','Josh Manson|D|85|Low','Jaden Schwartz|C|84|Low','Nicolas Roy|C|83|Med','Brett Kulak|D|82|Med','Logan O’Connor|RW|81|Med','Scott Wedgewood|G|81|High','Gavin Brindley|C|80|Med','Alex Barre-Boulet|C|79|Exact','Fedor Svechkov|C|79|Med','Sam Malinski|D|79|Med','Zachary L’Heureux|LW|79|Med','Nick Blankenburg|D|78|Med','Parker Kelly|C|78|Med','Zakhar Bardakov|C|78|Med','Fabian Lysell|RW|77|Med','Vinnie Hinostroza|C|77|Med','T.J. Tynan|C|76|Exact','Noah Juulsen|D|75|Med','Danil Gushchin|LW|74|Low','Adam Beckman|LW|73|Med','Taylor Makar|LW|73|Med','Alex Gagne|D|68|Med'
  ],
  CBJ: [
    'Zach Werenski|D|94|Exact','Kirill Marchenko|RW|89|Med','Conor Garland|RW|86|Med','Damon Severson|D|86|Med','Kent Johnson|C|86|Med','Sean Monahan|C|86|Med','Adam Fantilli|C|85|Med','Ivan Provorov|D|85|Med','Valeri Nichushkin|RW|85|Med','Charlie Coyle|C|84|Med','Denton Mateychuk|D|84|Med','Dmitri Voronkov|LW|84|Med','Cole Sillinger|C|82|Low','Dante Fabbro|D|82|Med','Danton Heinen|LW|82|Med','Egor Zamula|D|82|Med','Elvis Merzlikins|G|82|Med','Mathieu Olivier|RW|82|Low','Isac Lundestrom|C|80|Med','Miles Wood|LW|80|Med','Pheonix Copley|G|80|Med','Erik Gudbranson|D|79|Low','Ryan Lomberg|LW|79|Low','Brendan Smith|D|78|Med','Jake Christiansen|D|78|Med','Jet Greaves|G|73|Med','Owen Sillinger|C|73|Exact','Riley Bezeau|RW|71|Med'
  ],
  DAL: [
    'Mikko Rantanen|RW|94|Exact','Miro Heiskanen|D|93|Med','Jake Oettinger|G|90|Exact','Jason Robertson|LW|89|Med','Matt Duchene|C|89|Med','Thomas Harley|D|88|Med','Esa Lindell|D|87|Low','Roope Hintz|C|87|Med','Tyler Seguin|C|86|Med','Wyatt Johnston|C|86|Med','Jamie Benn|LW|85|High','Tyler Myers|D|84|Low','Casey DeSmith|G|83|Med','Michael Bunting|LW|82|Low','Radek Faksa|C|82|Med','Sam Steel|C|81|Med','Colin Blackwell|C|80|Low','Joel Kiviranta|LW|80|Med','Justin Hryckowian|C|79|Med','Lian Bichsel|D|79|Med','Nathan Bastian|RW|79|Med','Nils Lundkvist|D|79|Med','Oskar Back|C|79|Med','Adam Erne|LW|78|Med','Kyle Capobianco|D|77|Exact','Arttu Hyry|RW|75|Med','Artem Shlaine|C|69|Med'
  ],
  DET: [
    'Dylan Larkin|C|89|Med','Lucas Raymond|LW|89|Med','Alex DeBrincat|RW|88|Med','Moritz Seider|D|88|Med','Patrick Kane|RW|86|Med','Cam Talbot|G|85|Low','Justin Faulk|D|85|Med','David Perron|LW|84|Med','John Gibson|G|84|Med','Andrew Copp|C|83|Med','J.T. Compher|LW|83|Med','Marco Kasper|C|83|Med','Simon Edvinsson|D|83|Med','Viktor Arvidsson|LW|83|Med','Jacob Bernard-Docker|D|82|Low','Mason Appleton|C|82|Med','Michael Rasmussen|C|82|Med','Emmitt Finnie|C|81|Med','James van Riemsdyk|LW|81|High','Ben Chiarot|D|80|Med','Keegan Kolesar|RW|80|Med','Daniil Tarasov|G|79|Med','Jacob Bryson|D|79|Med','Travis Hamonic|D|78|Med','Albert Johansson|D|76|Low','Austin Watson|LW|75|Exact','Ronnie Attard|D|75|Med','Carter Mazur|LW|74|Med','Wilmer Skoog|C|74|Med','Eduards Tralmaks|RW|69|Exact','Cameron Butler|RW|68|Med'
  ],
  EDM: [
    'Connor McDavid|C|98|Exact','Leon Draisaitl|C|96|Exact','Evan Bouchard|D|88|High','Frederik Andersen|G|87|Med','Jake Walman|D|87|Med','Mattias Ekholm|D|87|Med','Zach Hyman|LW|87|Med','Ryan Nugent-Hopkins|C|86|Med','Tristan Jarry|G|86|Med','Connor Murphy|D|83|Med','Jason Dickinson|C|82|Med','Trent Frederic|C|82|Med','Adam Henrique|C|81|Med','Connor Ingram|G|81|Med','Kasperi Kapanen|RW|81|High','Mathieu Joseph|RW|81|Med','Matt Savoie|C|81|Med','Mattias Janmark|C|80|Med','Curtis Lazar|C|79|Low','Max Jones|LW|79|Med','Vasily Podkolzin|RW|79|Med','Colton Dach|C|78|Med','Ty Emberson|D|78|Med','Spencer Stastney|D|77|Med','Josh Samanski|C|76|Low','Ryan Shea|D|76|Med','Quinn Hutson|RW|75|Med'
  ],
  FLA: [
    'Aleksander Barkov|C|95|Exact','Matthew Tkachuk|LW|92|Exact','Sam Reinhart|C|92|Exact','Brad Marchand|C|89|High','Brady Tkachuk|LW|89|Med','Gustav Forsling|D|89|Med','Aaron Ekblad|D|87|Med','Carter Verhaeghe|C|87|Med','Jacob Markstrom|G|87|Med','Sam Bennett|C|87|Low','Seth Jones|D|87|Med','Anton Lundell|C|85|Med','Radko Gudas|D|84|Med','Eetu Luostarinen|C|82|Med','Lars Eller|C|82|High','Niko Mikkola|D|82|Med','Dmitry Kulikov|D|81|Med','Garnet Hathaway|RW|81|High','Luke Kunin|C|81|Med','Akira Schmid|G|80|Med','Johnny Beecher|C|80|Med','Tomas Nosek|LW|80|Med','Sam Lafferty|C|79|Med','Uvis Balinskis|D|79|Med','Jonah Gadjovich|LW|77|Med','Tobias Bjornfot|D|77|Low','Alexander Petrovic|D|75|Exact','Angus Crookshank|LW|75|Med','Bokondji Imama|LW|75|Med','Cole Schwindt|RW|75|Med','Mike Benning|D|75|Med','Sandis Vilmanis|LW|75|Med','Cole Reinhardt|LW|74|Med','Donovan Sebrango|D|71|Med','Emil Pieniniemi|D|66|Med'
  ],
  LAK: [
    'Artemi Panarin|LW|92|Exact','Adrian Kempe|RW|88|Med','Anze Kopitar|C|88|Low','Drew Doughty|D|88|Low','Darcy Kuemper|G|87|High','Kevin Fiala|LW|87|Med','Mats Zuccarello|RW|87|High','Quinton Byfield|RW|86|Med','Brandt Clarke|D|85|Med','Mikey Anderson|D|85|Med','Trevor Moore|LW|84|Med','Alex Laferriere|RW|83|Med','Erik Gustafsson|D|83|Med','Scott Laughton|LW|83|Med','Brian Dumoulin|D|82|Low','Erik Haula|LW|82|Low','Anton Forsberg|G|81|High','Cody Ceci|D|81|Low','Joel Armia|RW|81|Med','Joel Edmundson|D|81|High','Alex Turcotte|C|80|Med','Corey Perry|RW|80|High','Scott Perunovich|D|80|Med','Cole Guttman|C|76|Med','Jacob Moverare|D|75|Med','Jan Jenik|C|74|Med','Joe Hicketts|D|74|Exact','Samuel Helenius|C|74|Med','Lane Pederson|C|73|Exact','Taylor Ward|RW|73|Low','Kenny Connors|C|72|Med','Kirill Kirsanov|D|69|Med'
  ],
  MIN: [
    'Kirill Kaprizov|LW|95|Exact','Quinn Hughes|D|95|Med','Filip Gustavsson|G|89|Exact','Matt Boldy|LW|89|Med','Jonas Brodin|D|88|Med','Brock Faber|D|87|Med','Joel Eriksson Ek|C|86|Med','Jared Spurgeon|D|85|High','Blake Coleman|LW|84|Low','Bobby Brink|RW|83|Med','Marcus Foligno|LW|83|Low','Vladimir Tarasenko|RW|83|Med','Jeff Petry|D|82|High','Nick Foligno|LW|82|Low','Ryan Hartman|RW|82|Med','Marcus Johansson|LW|81|Med','Olli Maatta|D|81|Med','Robby Fabbri|C|81|Med','Zach Bogosian|D|81|High','Danila Yurov|RW|80|Med','Jesper Wallstedt|G|80|Med','Maxim Shabanov|RW|80|Med','Nico Sturm|C|80|Low','Nicolas Aube-Kubel|RW|80|Med','Yakov Trenin|C|80|Med','Calvin Pickard|G|79|High','Michael McCarron|RW|79|Low','Justin Kirkland|C|78|Med','Mason Shaw|C|77|Med','Daemon Hunt|D|76|Med','Dylan Gambrell|C|75|Exact','Carson Lambos|D|74|Med','Matt Kiersted|D|74|Exact','Viking Gustafsson Nyberg|D|73|Med','Jagger Joshua|LW|71|Low','Caedan Bankier|C|70|Med','David Spacek|D|69|Med','Roman Schmidt|D|68|Med'
  ],
  MTL: [
    'Nick Suzuki|C|91|Med','Cole Caufield|RW|88|Med','Lane Hutson|D|88|','Noah Dobson|D|88|Med','Mike Matheson|D|87|Med','Kaiden Guhle|D|86|Med','Phillip Danault|C|86|Med','Ivan Demidov|RW|85|','Juraj Slafkovsky|LW|85|Med','Patrik Laine|RW|85|Med','Sam Montembeault|G|85|Med','Jake Evans|C|84|Low','Oliver Kapanen|C|84|Med','Kirby Dach|C|83|High','Alexandre Carrier|D|82|Low','Josh Anderson|RW|82|Low','Alex Newhook|C|81|Med','Alexandre Texier|LW|80|Med','Arber Xhekaj|D|79|High','Zack Bolduc|RW|79|Med','Jayden Struble|D|78|Med','Brett Berard|LW|77|Med','Owen Beck|C|77|Med','Adam Engstrom|D|76|Med','David Reinbacher|D|75|Med','Maksymilian Szuber|D|75|Med','Alex Belzile|RW|74|Exact','Sam Poulin|RW|74|Med','Florian Xhekaj|LW|72|Med','Ethan Samson|D|70|Med','Owen Protz|D|66|Low'
  ],
  NSH: [
    'Roman Josi|D|92|Exact','Filip Forsberg|LW|89|Med','Juuse Saros|G|88|Exact','Brady Skjei|D|87|Med','Jonathan Marchessault|C|86|High','Steven Stamkos|C|86|Med','Ryan O’Reilly|C|85|Med','Nicolas Hague|D|84|Med','Ross Colton|C|84|High','Alexander Kerfoot|C|83|Med','Ilya Lyubushkin|D|82|Med','Luke Evangelista|RW|82|Med','Nick Perbix|D|82|Med','Nils Hoglander|LW|82|Med','Justin Barron|D|81|Med','Jack Drury|C|80|Low','Justus Annunen|G|80|Med','Matthew Wood|RW|80|Med','Ryan Ufko|D|79|Med','Tyson Jost|C|79|Med','Adam Edstrom|C|78|Med','Joakim Kemell|RW|76|Med','Kevin Gravel|D|76|Exact','Jack Ahcan|D|75|Exact','Oasiz Wiesblatt|C|75|Med','Reid Schaefer|LW|75|Med','Chase Bradley|LW|72|Med','Cole O’Hara|RW|72|Med','Ozzy Wiesblatt|C|72|Med','Adam Wilsby|D|71|Med','Christoffer Sedoff|D|69|Med','Hunter Skinner|D|69|Med','Isaac Ratcliffe|LW|69|High'
  ],
  NJD: [
    'Jack Hughes|C|92|High','Jesper Bratt|LW|91|Med','Nico Hischier|C|89|Med','Dougie Hamilton|D|88|Med','Jonas Siegenthaler|D|87|Med','Timo Meier|RW|87|Med','Brenden Dillon|D|86|High','Brett Pesce|D|86|Med','Luke Hughes|D|86|Med','Evan Rodrigues|C|84|Med','Stefan Noesen|RW|84|Low','Dawson Mercer|C|83|Med','Jake Allen|G|83|High','Nick Bjugstad|C|83|Med','Evgenii Dadonov|RW|82|High','Johnathan Kovacevic|D|82|Med','Arseny Gritsyuk|RW|81|Med','David Rittich|G|80|Med','Jesper Boqvist|C|80|Med','Cody Glass|C|79|Low','Connor Brown|RW|79|Med','Nico Daws|G|79|Med','Declan Chisholm|D|78|Med','Riley Tufte|LW|77|Exact','Vladislav Kolyachonok|D|76|Med','Marc McLaughlin|C|73|Low','Topias Vilen|D|71|Med','Etienne Morin|D|62|Med','Xavier Parent|C|62|Med'
  ],
  NYI: [
    'Ilya Sorokin|G|93|Exact','Matthew Schaefer|D|88|High','Adam Pelech|D|87|Med','Bo Horvat|C|87|Med','Ryan Pulock|D|87|Med','Mathew Barzal|C|86|Med','Brayden Schenn|C|85|Med','Alexander Romanov|D|84|Med','Anthony Duclair|LW|83|Low','Jean-Gabriel Pageau|C|83|Low','Kyle Palmieri|C|83|Med','Matias Maccelli|LW|83|Med','Simon Holmstrom|RW|83|Med','Emil Heineman|LW|82|Med','Semyon Varlamov|G|82|High','Adam Boqvist|D|81|Low','Carson Soucy|D|81|Med','Casey Cizikas|C|81|Med','Ondrej Palat|LW|81|High','Scott Mayfield|D|81|High','Vitek Vanecek|G|81|Med','Calum Ritchie|C|80|Med','Tony DeAngelo|D|80|Med','Ethan Bear|D|79|Exact','Isaiah George|D|79|Med','Mitchell Chaffee|RW|79|Med','Liam Foudy|C|77|Low','Victor Eklund|LW|76|Med','Kyle MacLean|C|75|Low','Matthew Kessel|D|74|Med','Matt Luff|RW|73|Exact'
  ],
  NYR: [
    'Igor Shesterkin|G|93|Exact','Adam Fox|D|91|Exact','J.T. Miller|LW|89|Med','Braden Schneider|D|86|Med','Mika Zibanejad|C|86|','Pavel Dorofeyev|LW|86|Med','Alexis Lafreniere|LW|85|Med','Marcus Pettersson|D|85|Med','Oliver Bjorkstrand|RW|85|Med','Sean Durzi|D|85|Med','Vladislav Gavrikov|D|85|Low','Will Cuylle|LW|85|Med','Jonathan Quick|G|83|High','Joonas Korpisalo|G|82|Low','Taylor Raddysh|RW|82|Med','Joe Veleno|C|81|Med','Noah Laba|C|80|Med','Tye Kartye|LW|80|Med','Gabe Perreault|RW|79|Med','Urho Vaakanainen|D|79|Med','Marc Del Gaizo|D|78|Med','Matt Rempe|C|77|Med','Adam Sykora|LW|76|Med','Dennis Cholowski|D|75|Low','Matthew Robertson|D|75|Med','Vincent Iorio|D|75|Med','Drew Fortescue|D|74|Med','Jaroslav Chmelar|RW|74|Med','Anton Blidh|LW|73|Exact','Massimo Rizzo|C|70|Med','Cole Beaudoin|C|69|Med','William Trudeau|D|69|Med'
  ],
  OTT: [
    'Tim Stutzle|C|90|High','Jake Sanderson|D|89|Med','Linus Ullmark|G|87|Med','Thomas Chabot|D|87|Med','Claude Giroux|RW|86|High','Drake Batherson|RW|86|Med','William Eklund|LW|86|Med','Dylan Cozens|C|85|Med','Artem Zub|D|84|Med','Warren Foegele|LW|84|Med','Andre Burakovsky|LW|83|Med','Fabian Zetterlund|LW|83|Med','Jordan Spence|D|83|Med','Samuel Ersson|G|83|Med','Shane Pinto|C|83|Med','Arthur Kaliyev|RW|81|Med','James Reimer|G|81|Low','Ridly Greig|C|81|Med','Michael Amadio|RW|80|Med','Philip Tomasino|C|80|Med','Nick Cousins|C|79|Low','Sammy Blais|LW|79|High','Kurtis MacDermid|LW|77|Med','Stephen Halliday|C|77|Med','Lassi Thomson|D|76|Med','Nikolas Matinpalo|D|76|Med','Olle Lycksell|RW|76|Med','Tyler Kleven|D|76|Med','Carter Yakemchuk|D|75|Med','Ryan Suzuki|C|75|Med','Xavier Bourgault|RW|75|Med','Cameron Crotty|D|74|Med','Graeme Clarke|RW|74|Med','Leevi Merilainen|G|74|Med','Christian Kyrou|D|73|Med','Hayden Hodgson|RW|69|Low','Oskar Pettersson|RW|69|Med','Tyler Boucher|RW|69|Low','Philippe Daoust|C|66|Med'
  ],
  PHI: [
    'Matvei Michkov|RW|88|','Travis Konecny|RW|88|Med','Travis Sanheim|D|88|Med','Joseph Woll|G|85|Med','Sean Couturier|C|85|Med','Cam York|D|84|Med','David Jiricek|D|84|Med','Owen Tippett|RW|84|Med','Noah Cates|LW|83|Med','Trevor Zegras|C|83|Med','Dan Vladar|G|82|Med','Jamie Drysdale|D|82|Med','Nick Seeler|D|82|Med','Rasmus Ristolainen|D|81|Med','Tyson Foerster|RW|81|Med','Christian Dvorak|LW|80|Med','Carl Grundstrom|RW|79|Med','Luke Glendening|C|79|High','Porter Martone|RW|79|Med','Simon Benoit|D|79|Low','Denver Barkey|C|78|Med','Noel Acciari|C|78|Low','Alex Bump|LW|77|Low','Anthony Richard|C|77|Exact','Helge Grans|D|77|Med','Nikita Grebenkin|RW|77|Med','Jett Luchanko|C|75|Med','Oliver Bonk|D|75|Med','Jacob Gaucher|C|74|Med','Garrett Wilson|LW|73|Exact','Danila Klimovich|RW|72|Med','Hunter McDonald|D|71|Med','Oscar Eklind|LW|70|Exact'
  ],
  PIT: [
    'Sidney Crosby|C|95|Exact','Erik Karlsson|D|88|Med','Evgeni Malkin|C|88|High','Kris Letang|D|86|High','Samuel Girard|D|86|Med','Bryan Rust|RW|85|Med','Rickard Rakell|RW|85|Med','Yegor Chinakhov|RW|84|Med','Kevin Hayes|RW|83|Med','Andrei Kuzmenko|LW|82|Med','Anthony Mantha|RW|82|Med','Ben Kindel|C|82|Med','Justin Brazeau|RW|82|Med','Tommy Novak|C|82|Med','Trevor van Riemsdyk|D|82|Med','Nicholas Robertson|LW|81|Med','Ryan Graves|D|81|Med','Arturs Silovs|G|80|Med','Blake Lizotte|C|80|Med','Connor Dewar|C|79|Med','David Gustafsson|C|79|Med','Elmer Soderblom|LW|79|Med','Hendrix Lapierre|C|79|Low','Filip Hallander|C|78|Med','Kaedan Korczak|D|78|Med','Rutger McGroarty|RW|78|High','Rafael Harvey-Pinard|LW|77|Med','Caleb Jones|D|76|Med','Declan Carlile|D|76|Med','Ville Koivunen|RW|76|Med','Avery Hayes|RW|75|Med','Joona Koppanen|LW|75|Exact','Jake Livanavage|D|74|Med','Ilya Solovyov|D|73|Med','Oliver Okuliar|LW|72|High'
  ],
  SJS: [
    'Macklin Celebrini|C|93|Med','Jacob Trouba|D|86|Med','Darnell Nurse|D|85|Med','Dmitry Orlov|D|85|Med','Mason Marchment|LW|85|Med','Tyler Toffoli|C|85|Med','Michael Kesselring|D|84|Med','Alex Wennberg|C|83|Med','Will Smith|C|83|','Kiefer Sherwood|LW|82|Med','Nick Leddy|D|82|Med','Yaroslav Askarov|G|82|','Adam Gaudette|RW|81|Med','Alex Nedeljkovic|G|81|Med','Eric Comrie|G|81|Med','Barclay Goodrow|RW|80|Med','Brett Leason|RW|80|Med','Philipp Kurashev|C|80|Low','Ty Dellandrea|C|79|Med','John Klingberg|D|78|Low','Michael Misa|C|78|Med','Pavol Regenda|LW|78|High','Sam Dickinson|D|78|Med','Nolan Allan|D|77|Med','Collin Graf|RW|75|Low','Ryan Reaves|RW|75|Med','Zack Ostapchuk|C|75|Med','Ethan Cardwell|RW|74|Med','Kyle Keyser|G|73|Low'
  ],
  SEA: [
    'Brandon Montour|D|87|Med','Vince Dunn|D|87|Med','Jared McCann|LW|86|Med','Chandler Stephenson|C|85|Med','Joey Daccord|G|85|High','Jordan Eberle|RW|85|Low','Matty Beniers|C|85|Med','Adam Larsson|D|84|Med','Eeli Tolvanen|RW|84|Low','Ryan Lindgren|D|84|Med','Ryker Evans|D|84|Med','Frederick Gaudreau|C|83|Med','Kaapo Kakko|RW|83|Low','Philipp Grubauer|G|83|Low','Shane Wright|C|82|Med','Bobby McMann|C|81|Low','Mackie Samoskevich|RW|80|Med','Matt Murray|G|80|Med','Cale Fleury|D|78|Low','Joshua Mahura|D|78|Med','Ben Meyers|C|77|Med','Berkly Catton|C|77|Med','Ryan Winterton|C|76|Med','Curtis Douglas|C|75|Med','Jacob Melanson|RW|75|Med','Jani Nyman|RW|75|Med','Logan Morrison|C|75|Med','Oscar Fisker Molgaard|C|75|Med'
  ],
  STL: [
    'Robert Thomas|C|89|Med','Colton Parayko|D|88|Med','Brandon Carlo|D|86|Med','Connor McMichael|C|86|Low','Dylan Holloway|LW|86|Med','Jordan Binnington|G|86|Low','Mason McTavish|C|85|High','Pavel Buchnevich|LW|85|Med','Cam Fowler|D|84|Low','Jake Neighbours|LW|84|Low','Philip Broberg|D|84|Med','Pius Suter|C|83|Med','Jimmy Snuggerud|RW|82|Med','Joel Hofer|G|82|Med','Oskar Sundqvist|C|82|Med','Alexey Toropchenko|RW|80|Med','Dillon Dube|C|80|Med','Jonatan Berggren|RW|80|Med','Dalibor Dvorsky|RW|79|Med','Nathan Walker|LW|78|Med','Tyler Tucker|D|77|Med','Calle Rosen|D|76|Exact','Logan Mailloux|D|76|Med','Ross Johnston|LW|76|Med','Jack Finley|C|75|Med','Hugh McGing|RW|74|Exact','Dylan Peterson|C|72|Med','Julien Gauthier|RW|71|Exact'
  ],
  TBL: [
    'Nikita Kucherov|RW|96|Exact','Andrei Vasilevskiy|G|94|Exact','Victor Hedman|D|92|Exact','Brandon Hagel|LW|90|Med','Brayden Point|C|89|Med','Jake Guentzel|C|89|Med','John Carlson|D|88|Med','Anthony Cirelli|C|86|Med','Erik Cernak|D|85|Med','Ryan McDonagh|D|85|Med','J.J. Moser|D|84|Med','Yanni Gourde|C|82|Med','Ilya Mikheyev|RW|81|High','Conor Geekie|C|80|Med','Jonas Johansson|G|80|Med','Charle-Edouard D’Astous||79|Exact','Maxwell Crozier|D|79|Med','Pontus Holmberg|RW|79|Med','Zemgus Girgensons|C|79|Low','Dennis Hildeby|G|78|Med','Dominic James|C|78|Med','Emil Lilleberg|D|78|Med','Jansen Harkins|C|77|Med','Mads Sogaard|G|77|Med','Gage Goncalves|C|75|Med','Jeffrey Viel|LW|75|Exact','Nick Abruzzese|C|74|Med','Scott Sabourin|RW|73|Exact','Michael Callahan|D|72|Med','Maxim Groshev|D|71|Med'
  ],
  TOR: [
    'William Nylander|RW|93|Exact','Auston Matthews|C|92|Exact','John Tavares|C|88|High','Matthew Knies|LW|87|Med','Morgan Rielly|D|87|Med','Sergei Bobrovsky|G|87|High','Anthony Stolarz|G|85|Low','Chris Tanev|D|85|Low','Jake McCabe|D|85|Med','Nicholas Paul|LW|85|Med','Darren Raddysh|D|84|Low','Jack Roslovic|C|84|Med','Oliver Ekman-Larsson|D|84|Med','Calle Jarnkrok|C|82|Med','Colton Sissons|C|82|Low','Max Domi|C|82|Med','Dakota Joshua|C|81|Low','Teddy Blueger|C|81|Med','Brandon Duhaime|RW|80|Med','Emil Andrae|D|80|Med','Steven Lorentz|C|79|Med','Troy Stecher|D|79|Med','Bo Groulx|C|78|Med','Zack MacEwen|RW|78|Med','Vinni Lettieri|C|76|Exact','Philippe Myers|D|75|Med','Cole McWard|D|73|Med','Ryan Tverberg|C|72|Med','Henrik Rybinski|RW|69|Med'
  ],
  UTA: [
    'Clayton Keller|C|90|Med','Logan Cooley|C|88|Med','MacKenzie Weegar|D|88|Med','Mikhail Sergachev|D|88|Med','Vincent Trocheck|C|88|Med','Dylan Guenther|RW|87|Med','Nick Schmaltz|C|86|Med','Karel Vejmelka|G|85|Med','Anders Lee|LW|84|Med','John Marino|D|84|Med','Barrett Hayton|C|83|Med','Brandon Tanev|LW|83|Low','Jack McBain|C|82|Low','Lawson Crouse|LW|82|High','Nate Schmidt|D|82|Low','Kevin Stenlund|C|80|Med','Michael Carcone|LW|80|Med','Andrew Peeke|D|79|Low','Daniil But|LW|78|Med','Dmitri Simashev|D|78|Med','Kailer Yamamoto|RW|78|Med','Liam O’Brien|C|78|Low','Maveric Lamoureux|D|78|Med','Andrew Agozzino|LW|76|Exact','Joshua Roy|RW|76|Med','Kevin Rooney|C|76|Med','Nick DeSimone|D|76|Med','Ben McCartney|LW|70|Med','Cameron Hebig|C|67|Exact','Terrell Goldsmith|D|62|Med'
  ],
  VAN: [
    'Thatcher Demko|G|88|Med','Elias Pettersson|C|87|Med|Top Line','Brock Boeser|RW|86|Med','Filip Hronek|D|86|Med','Marco Rossi|C|86|Med','Jake DeBrusk|LW|85|Med','Jamie Oleksiak|D|85|Med','Evander Kane|LW|84|Med','Filip Chytil|C|84|Med','Kevin Lankinen|G|84|Med','Luke Schenn|D|84|Med','Brendan Gallagher|RW|83|Med','Paul Cotter|C|83|Med','Pierre-Olivier Joseph|D|83|Med','Zeev Buium|D|83|Med','Drew O’Connor|LW|81|Low','Derek Forbort|D|80|Med','Tom Willander|D|80|Med','Liam Öhgren|LW|79|Med','Max Sasson|C|79|Med','Aatu Raty|C|78|Med','Elias Pettersson|D|78|Med','Nils Aman|C|78|Med','Victor Mancini|D|78|Med','Akil Thomas|C|76|Med','Matt Stienburg|C|76|Med','Trey Fix-Wolansky|RW|76|Low','Linus Karlsson|C|75|Med','Braeden Cootes|C|73|Med','Cole Clayton|D|69|Med'
  ],
  VGK: [
    'Jack Eichel|C|94|High','Mitch Marner|RW|92|Exact','Mark Stone|RW|89|Low','Noah Hanifin|D|89|Med','Rasmus Andersson|D|88|Med','Shea Theodore|D|88|High','Carter Hart|G|87|Med','Ivan Barbashev|C|86|Med','Tomas Hertl|C|86|Med','Brayden McNabb|D|85|Med','Adin Hill|G|84|Med','Reilly Smith|RW|84|Med','William Karlsson|C|84|Low','Brett Howden|C|81|Med','Jeremy Lauzon|D|81|Med','Nic Dowd|C|81|Low','Victor Olofsson|LW|81|Med','Alexander Holtz|RW|80|Med','Braeden Bowman|RW|80|Low','Brandon Saad|LW|80|Low','Ben Hutton|D|78|Med','Dylan Coghlan|D|78|Med','Parker Wotherspoon|D|77|Med','Ville Heinola|D|77|Med','Jonas Rondbjerg|RW|76|Med','Raphael Lavoie|C|76|Med','Adam Ginning|D|75|Med','Jaycob Megna|D|75|Low','Jeremy Davies|D|75|Exact','Lukas Cormier|D|75|Med','Tanner Laczynski|C|75|Med','Trevor Connelly|LW|74|Med','Kai Uchacz|C|73|Med','Marc Gatcomb|C|73|Med','Antti Tuomisto|D|70|Med'
  ],
  WSH: [
    'Alex Ovechkin|LW|90|Med','Dylan Strome|C|89|Med','Jordan Kyrou|RW|88|Med','Alex Tuch|RW|87|Med','Aliaksei Protas|C|87|High','Jakob Chychrun|D|87|Med','Logan Thompson|G|86|Med','Martin Fehervary|D|86|High','Pierre-Luc Dubois|LW|86|Med','Tom Wilson|RW|86|Med','Matt Roy|D|84|Low','Rasmus Sandin|D|84|Med','Boone Jenner|C|83|Med','Charlie Lindgren|G|83|Med','David Kampf|C|82|Med','Ryan Leonard|RW|82|Med','Timothy Liljegren|D|82|Low','Anthony Beauvillier|LW|81|Low','Jonny Brodzinski|C|80|Med','Justin Holl|D|80|Med','Vincent Desharnais|D|79|Med','Cole Hutson|D|78|Med','Ivan Miroshnichenko|LW|77|Med','Josh Dunne|C|77|Low','Dylan McIlrath|D|75|Low','Ilya Protas|LW|75|Med','Ethen Frank|C|71|Med','Justin Sourdif|RW|68|Med'
  ],
  WPG: [
    'Connor Hellebuyck|G|92|Exact','Kyle Connor|LW|92|Exact','Mark Scheifele|C|92|Exact','Josh Morrissey|D|91|Exact','Neal Pionk|D|87|High','Gabriel Vilardi|C|86|Med','Adam Lowry|C|84|Med','Cole Perfetti|C|84|Med','Dylan DeMelo|D|84|Med','Dylan Samberg|D|84|Med','Nino Niederreiter|RW|84|Med','Stuart Skinner|G|84|Med','Gustav Nyquist|RW|83|Med','Mario Ferraro|D|83|Med','Vladislav Namestnikov|C|83|Med','Alex Iafallo|LW|82|Low','Colin Miller|D|81|Low','Morgan Barron|C|80|Med','Haydn Fleury|D|79|Low','Noah Gregor|LW|79|Med','Cole Koepke|LW|78|Exact','Isak Rosen|RW|78|Med','Walker Duehr|RW|78|Med','Jack St. Ivany|D|77|Med','Isaak Phillips|D|76|Med','Isaac Poulter|G|75|Med','Nikita Chibrikov|RW|75|Med','Parker Ford|C|75|Med'
  ]
};
