#!/usr/bin/env python3
"""glb2js: wrap a binary .glb as a JS file that sets a base64 global (works over file:// where XHR is blocked)."""
import base64,sys
src,dst,name=sys.argv[1],sys.argv[2],sys.argv[3]
b=base64.b64encode(open(src,'rb').read()).decode()
open(dst,'w').write('/* generated by glb2js from %s */\nwindow.%s="%s";\n'%(src.split('/')[-1],name,b))
