
/* ---------------- pick card data ---------------- */
var CITIES={CAN:['Toronto, ON','Kitchener, ON','Sudbury, ON','Kingston, ON','London, ON','Ottawa, ON','Sault Ste. Marie, ON','Winnipeg, MB','Brandon, MB','Regina, SK','Saskatoon, SK','Calgary, AB','Edmonton, AB','Red Deer, AB','Kelowna, BC','Burnaby, BC','Kamloops, BC','Halifax, NS','Moncton, NB','St. John\'s, NL'],QUE:['Quebec City, QC','Montreal, QC','Sherbrooke, QC','Rimouski, QC','Gatineau, QC','Trois-Rivieres, QC'],
 USA:['Minneapolis, MN','Duluth, MN','Warroad, MN','Boston, MA','Hingham, MA','Buffalo, NY','Rochester, NY','Detroit, MI','Plymouth, MI','Grand Rapids, MI','Chicago, IL','Madison, WI','Fargo, ND','St. Louis, MO','Pittsburgh, PA','Denver, CO','Dallas, TX','Scottsdale, AZ','Anchorage, AK','San Jose, CA'],
 SWE:['Stockholm','Gothenburg','Malmo','Ornskoldsvik','Skelleftea','Lulea','Vaxjo','Jonkoping','Linkoping','Karlstad'],FIN:['Helsinki','Turku','Tampere','Oulu','Espoo','Lahti','Jyvaskyla','Rauma','Pori','Kuopio'],RUS:['Moscow','St. Petersburg','Yaroslavl','Kazan','Omsk','Chelyabinsk','Ufa','Magnitogorsk','Nizhny Novgorod','Novosibirsk'],
 CZE:['Prague','Brno','Pardubice','Plzen','Liberec','Trinec','Zlin','Kladno'],SVK:['Bratislava','Kosice','Nitra','Trencin','Zvolen','Banska Bystrica'],SUI:['Zurich','Bern','Lugano','Davos','Geneva','Zug'],GER:['Mannheim','Cologne','Munich','Berlin','Fussen','Landshut'],LAT:['Riga','Liepaja','Daugavpils'],NOR:['Oslo','Stavanger','Lillehammer'],DEN:['Herning','Aalborg','Copenhagen'],AUT:['Vienna','Salzburg','Klagenfurt','Innsbruck'],BLR:['Minsk','Grodno','Vitebsk'],KAZ:['Ust-Kamenogorsk','Astana','Karaganda']};
var NATION={SWE:'Sweden',FIN:'Finland',RUS:'Russia',CZE:'Czechia',SVK:'Slovakia',SUI:'Switzerland',GER:'Germany',LAT:'Latvia',NOR:'Norway',DEN:'Denmark',AUT:'Austria',BLR:'Belarus',KAZ:'Kazakhstan'};
function natCode(p){var n=String(p.nationality||'').toUpperCase();if(CITIES[n])return n;var m={CANADA:'CAN',USA:'USA','UNITED STATES':'USA',SWEDEN:'SWE',FINLAND:'FIN',RUSSIA:'RUS',CZECHIA:'CZE','CZECH REPUBLIC':'CZE',SLOVAKIA:'SVK',SWITZERLAND:'SUI',GERMANY:'GER',LATVIA:'LAT',NORWAY:'NOR',DENMARK:'DEN',AUSTRIA:'AUT',BELARUS:'BLR',KAZAKHSTAN:'KAZ'};return m[n]||'CAN';}
S.birthplace=function(p){if(p.birthplace)return p.birthplace;var n=natCode(p),r=rng('born|'+p.id+'|'+p.name),list=n==='CAN'&&/QMJHL/.test(p.league||'')&&r()<0.7?CITIES.QUE:CITIES[n];var c=list[Math.floor(r()*list.length)];return NATION[n]?c+', '+NATION[n]:c+(n==='USA'?', USA':', CAN');};
var POSN={C:'center',LW:'left winger',RW:'right winger',D:'defenseman',G:'goaltender'};
var STR={F:['soft hands in tight','an elite release','high-end vision','a relentless forecheck','a deceptive first step','a heavy, accurate shot','strong two-way instincts','a natural finisher\'s touch'],D:['a calm first pass','four-way mobility','a heavy point shot','a nasty edge in front of his net','excellent gap control','a quarterback\'s vision on the power play'],G:['quiet, efficient movement','elite rebound control','great size and reach','a battler\'s compete level','sharp post-to-post speed']};
var WEAK={F:['needs to add strength on the puck','has to improve his first three strides','his defensive reads are still a work in progress','his consistency comes and goes','has to shoot more'],D:['decision-making under pressure needs work','has to get stronger in the corners','tends to over-commit in the neutral zone','his footwork needs refining'],G:['tracking through traffic needs work','can be beaten glove side','has to cut down on rebounds','needs more reps against men']};
function grp(p){return p.pos==='D'?'D':p.pos==='G'?'G':'F';}
S.tier=function(p){var v=Number(p.potential)||Number(p.projection)||70,k=grp(p),L={F:['Franchise forward','First-line forward','Top-six forward','Middle-six forward','Bottom-six forward','Long-term project'],D:['No. 1 defenseman','Top-pair defenseman','Top-four defenseman','Second-pair defenseman','Third-pair defenseman','Long-term project'],G:['Franchise goaltender','Future starter','Future starter','1B goaltender','Backup goaltender','Long-term project']}[k],i=v>=90?0:v>=86?1:v>=82?2:v>=77?3:v>=72?4:5;return L[i];};
S.grade=function(v){v=Number(v)||70;return v>=90?'A+':v>=87?'A':v>=84?'A-':v>=81?'B+':v>=78?'B':v>=75?'B-':v>=72?'C+':'C';};
function ft(cm){if(!cm)return '';var i=Math.round(cm/2.54);return Math.floor(i/12)+'\''+(i%12)+'"';}
S.blurb=function(p){var r=rng('blurb|'+p.id),k=grp(p),h=Number(p.heightCm)||183,frame=h>=191?'big':h>=185?'pro-sized':h<=175?'undersized':'average-sized',shot=p.shoots?(p.shoots==='L'?'left-shot ':'right-shot '):'',pos=POSN[p.pos]||'forward',s=p.stats||{},team=p.amateurTeam||p.league||'his club';
 var lead=frame+' '+(k==='G'?'':shot)+pos,a=(/^[aeiou]/i.test(lead)?'An ':'A ')+lead+' with '+STR[k][Math.floor(r()*STR[k].length)]+'.';
 var b=k==='G'?(s.gp?' Posted a '+String(s.svp).replace(/^0/,'')+' save percentage in '+s.gp+' games with '+team+'.':''):(s.gp?' Put up '+s.pts+' points in '+s.gp+' games with '+team+'.':'');
 return a+b+' The knock: '+WEAK[k][Math.floor(r()*WEAK[k].length)]+'.';};
function teamOf(id){var x=X();var t=x&&x.team?x.team(id):null;return t||{id:id,name:id,color:'#FFB81C',secondary:'#111111'};}
function hexOk(c,f){return /^#[0-9a-f]{6}$/i.test(c||'')?c:f;}
function lum(h){var n=parseInt(h.slice(1),16);return 0.299*(n>>16)+0.587*((n>>8)&255)+0.114*(n&255);}
S.colors=function(id){var t=teamOf(id),a=hexOk(t.color,'#FFB81C'),b=hexOk(t.secondary,'#111111');var accent=lum(a)>40?a:b;return {primary:a,secondary:b,accent:lum(accent)>40?accent:'#FFB81C'};};
