
/* ---------------- broadcast engine ---------------- */
var queue=[],cur=null,root=null,stage=null,raf=0,last=0,paused=false,hold=null,stripTimer=0,tick=[];
S._queue=queue;
var DUR={
 full:[['clock',1.5],['podium',2.3],['card',2.8],['walk',3.0],['jersey',1.8],['handshake',1.8],['photo',1.5],['board',1.5]],
 user:[['clock',2.2],['podium',3.2],['card',4.2],['walk',4.2],['jersey',2.6],['handshake',2.6],['photo',2.2],['question',Infinity],['debrief',Infinity],['result',3.2],['board',2.4]],
 talk:[['question',Infinity],['debrief',Infinity],['result',3.2]],
 userclock:[['clock',2.6]],quick:[['quick',1.4]],ticker:[['strip',0.2]]};
var STAGE_SCENES={podium:1,walk:1,jersey:1,handshake:1,photo:1,question:1,debrief:1,result:1};
function game(){var x=X(),c=x&&x.cur&&x.cur();return c&&c.game;}
function nmT(id){return teamOf(id).name;}
function draftYear(g){var st=g&&g.offseason&&g.offseason.liveDraft;return st&&st.year||(A()&&A().draftYearOf?A().draftYearOf(g):2027);}
S.picked=function(g,row,p,how){try{if(!g||!g.offseason||!X())return;var year=draftYear(g),user=row.owner===g.team,base={overall:row.overall,round:row.round,slot:row.slot,owner:row.owner,origin:row.origin,p:p,year:year};
 if(user&&how==='manual'){var ctx=S.context(g,p,row.owner,row.overall,year),q=S.pickQuestion(g,p,ctx,true);if(q&&p.ctfoDraft)p.ctfoDraft.talk={v:1,qid:q.id,pending:true,year:year,owner:row.owner,overall:row.overall,user:true};base.kind=S.settings().mode==='off'?'talk':'user';enqueue(base);return;}
 if(user){S.cpuDecide(g,p,row,year);return;}
 if(S._silent)return;var m=S.settings().mode;if(m==='off')return;base.kind=S._ff?'ticker':row.round===1?'full':m==='full'?'quick':'ticker';enqueue(base);}catch(e){console.error('draft show',e);}};
function enqueue(it){queue.push(it);if(!cur)setTimeout(next,40);}
function next(){if(cur)return;var it=queue.shift(),strip=false;
 if(it&&it.kind==='quick'&&queue.filter(function(x){return x.kind==='quick';}).length>12){it.kind='ticker';queue.forEach(function(x){if(x.kind==='quick')x.kind='ticker';});}
 while(it&&it.kind==='ticker'){addTick(it);strip=it;it=queue.shift();}
 if(!it){if(strip)showStrip(strip);else close();return;}
 cur=it;if(it.kind==='user'||it.kind==='talk'||it.kind==='userclock')S._ff=false;it.phases=DUR[it.kind].map(function(a){return {n:a[0],d:a[1]};});it.pi=0;open();enter();}
function showStrip(it){cur={kind:'ticker',owner:it.owner,year:it.year,phases:[{n:'strip',d:0.2}],pi:0,p:it.p};open();root.dataset.scene='strip';root.querySelector('.cs-scene').innerHTML='';root.querySelector('.cs-lower').innerHTML='';renderTick();cur=null;close();}
function needsStage(it){return it.phases.some(function(ph){return STAGE_SCENES[ph.n];});}
function open(){if(stripTimer){clearTimeout(stripTimer);stripTimer=0;}if(!root){root=document.createElement('div');root.id='ctfo-show';root.className='cs-root';root.setAttribute('role','dialog');root.setAttribute('aria-label','NHL Draft broadcast');
  root.innerHTML='<div class="cs-stage"></div><div class="cs-wash"></div><div class="cs-scene"></div><div class="cs-flash"></div><div class="cs-lower"></div><div class="cs-top"><div class="cs-brand"><i></i><b class="cs-year"></b><span>LIVE</span></div><div class="cs-ctrl"><button type="button" class="cs-btn" data-cs="skip">Skip this pick</button><button type="button" class="cs-btn" data-cs="ff">Sim to my next pick</button><button type="button" class="cs-btn" data-cs="speed"></button><label class="cs-pres">Presentation <select data-cs-pres><option value="full">Full</option><option value="r1">Round 1 only</option><option value="off">Off</option></select></label></div></div><div class="cs-ticker"><b>THE PICKS</b><div class="cs-tick-list"></div></div>';
  document.body.appendChild(root);}
 var it=cur,c=S.colors(it.owner);root.hidden=false;root.classList.remove('cs-out');root.dataset.kind=it.kind;root.style.setProperty('--cs-team',c.primary);root.style.setProperty('--cs-team2',c.secondary);root.style.setProperty('--cs-accent',c.accent);
 root.querySelector('.cs-year').textContent=it.year+' NHL DRAFT';syncCtrl();
 if(stage&&stage.kind==='2d'&&S._ready3d()){stage.dispose();stage=null;}if(needsStage(it)){if(!stage)stage=makeStage(root.querySelector('.cs-stage'));if(stage)stage.setInfo(it,c);}
 if(!raf){last=0;raf=requestAnimationFrame(loop);}}
function syncCtrl(){if(!root)return;var s=S.settings(),it=cur||{},userish=it.kind==='user'||it.kind==='talk';root.querySelector('[data-cs="speed"]').textContent='Speed '+s.speed+'x';root.querySelector('[data-cs-pres]').value=s.mode;
 var sk=root.querySelector('[data-cs="skip"]');sk.textContent=it.kind==='userclock'?'Make your pick':'Skip this pick';var ph=it.phases&&it.phases[it.pi];sk.hidden=userish&&ph&&/question|debrief/.test(ph.n);root.querySelector('[data-cs="ff"]').hidden=userish||it.kind==='userclock';}
function close(){cur=null;if(!root)return;if(stage){try{stage.dispose();}catch(e){}stage=null;root.querySelector('.cs-stage').innerHTML='';}
 var stripOnly=root.dataset.kind==='ticker';if(raf){cancelAnimationFrame(raf);raf=0;}root.classList.add('cs-out');
 stripTimer=setTimeout(function(){stripTimer=0;if(!cur&&root){root.hidden=true;root.classList.remove('cs-out');}},stripOnly?2600:260);setTimeout(checkClock,stripOnly?60:300);}
function loop(ts){raf=requestAnimationFrame(loop);var dt=last?Math.min(0.1,(ts-last)/1000):0;last=ts;if(!cur||!cur.phases)return;var ph=cur.phases[cur.pi];if(!ph)return;
 if(stage&&stage.kind==='2d'&&S._ready3d()&&root){try{stage.dispose();stage=makeStage(root.querySelector('.cs-stage'));stage.setInfo(cur,S.colors(cur.owner));root.querySelector('.cs-stage').style.visibility=STAGE_SCENES[ph.n]?'visible':'hidden';}catch(e){console.error('draft stage swap',e);}}/* v9.1: models finished loading mid-item */
 if(!paused)cur.t+=dt*S.settings().speed;var f=ph.d===Infinity?0:Math.min(1,cur.t/ph.d);if(hold&&hold.n===ph.n&&f>=hold.f&&!paused){paused=true;f=hold.f;cur.t=f*ph.d;S._held=ph.n;}
 try{update(ph,f,cur.t);if(stage&&STAGE_SCENES[ph.n])stage.render(ph.n,f,cur.t,dt,cur);}catch(e){console.error('draft show frame',e);finishItem();return;}
 if(f>=1&&!paused)advance();}
function advance(){cur.pi++;if(cur.pi>=cur.phases.length){finishItem();return;}enter();}
function finishItem(){cur=null;paused=false;if(queue.length)next();else{S._ff=false;close();}}
S._finish=finishItem;
function jump(name){var i=cur.phases.findIndex(function(p){return p.n===name;});if(i>=0){cur.pi=i;enter();return true;}return false;}
function enter(){var it=cur,ph=it.phases[it.pi];it.t=0;root.dataset.scene=ph.n;syncCtrl();var sc=root.querySelector('.cs-scene'),lo=root.querySelector('.cs-lower'),p=it.p,x=X(),tm=nmT(it.owner),user=it.kind==='user'||it.kind==='talk'||it.kind==='userclock';
 root.querySelector('.cs-stage').style.visibility=STAGE_SCENES[ph.n]&&stage?'visible':'hidden';lo.innerHTML='';sc.innerHTML='';lo.className='cs-lower';
 var gmLabel=user?'YOU · GENERAL MANAGER':'GENERAL MANAGER · '+tm.toUpperCase();
 if(ph.n==='clock'){var from=it.owner!==it.origin?'<small class="cs-from">Pick acquired from the '+esc(nmT(it.origin))+'</small>':'';sc.innerHTML='<div class="cs-clock"><div class="cs-crest">'+x.officeMark(it.owner,'cs-crest-mark')+'</div><p class="cs-kick">'+(it.kind==='userclock'?'YOU ARE ON THE CLOCK':'ON THE CLOCK')+'</p><h1>'+esc(tm)+'</h1><div class="cs-clock-meta"><span>ROUND '+it.round+'</span><b>PICK '+it.slot+'</b><span>'+ordinal(it.overall).toUpperCase()+' OVERALL</span></div>'+from+'<div class="cs-bar"><i></i></div><div class="cs-timer">2:30</div>'+(it.kind==='userclock'?'<button type="button" class="cs-btn cs-gold" data-cs="pick">Make your pick →</button>':'')+'</div>';}
 else if(ph.n==='podium'){lo.innerHTML=l3(gmLabel,tm);sc.innerHTML='<div class="cs-speech"><p class="cs-typed"></p><span class="cs-dots"><i></i><i></i><i></i></span></div>';it.line='With the '+ordinal(it.overall)+' pick in the '+it.year+' NHL Draft, the '+tm+' are proud to select\u2026';}
 else if(ph.n==='card'||ph.n==='quick'){sc.innerHTML=card(it,ph.n==='quick');if(ph.n==='card'||ph.n==='quick')addTick(it);}
 else if(ph.n==='walk'){lo.innerHTML=l3(esc(p.name).toUpperCase()+' · '+esc(p.pos),'Making his way to the stage');}
 else if(ph.n==='jersey'){lo.innerHTML=l3(esc(p.name).toUpperCase(),'Pulling on the '+esc(tm)+' sweater');}
 else if(ph.n==='handshake'){lo.innerHTML='<div class="cs-l3 cs-duo"><span class="cs-l3-k">Welcome to the '+esc(tm)+'</span><div class="cs-duo-row"><div class="cs-duo-p"><small>'+esc(ordinal(it.overall))+' overall · '+esc(p.pos)+'</small><b class="cs-duo-name">'+esc(p.name)+'</b></div><div class="cs-duo-g"><small>'+(user?'You · general manager':'General manager')+'</small><b class="cs-duo-gm">'+esc(tm)+' GM</b></div></div></div>';}
 else if(ph.n==='photo'){lo.innerHTML=l3(ordinal(it.overall).toUpperCase()+' OVERALL · '+esc(tm).toUpperCase(),esc(p.name)+' · '+esc(p.pos)+' · '+esc(p.amateurTeam||p.league||''));}
 else if(ph.n==='question'){sc.innerHTML=questionHtml(it);}
 else if(ph.n==='debrief'){sc.innerHTML=debriefHtml(it);}
 else if(ph.n==='result'){var t=p.ctfoDraft&&p.ctfoDraft.talk||{},o=OUT[t.outcome]||OUT.return;lo.className='cs-lower cs-result cs-'+o[1];lo.innerHTML=l3('DRAFT STAGE · '+esc(p.name).toUpperCase(),'<span class="cs-res-t">'+esc(S.outcomeTitle(t,p))+'</span>','<small>'+esc(S.outcomeDetail(t,p,game()))+'</small>');if(t.outcome==='now')sc.innerHTML='<div class="cs-stamp">SIGNED · ENTRY-LEVEL CONTRACT</div>';}
 else if(ph.n==='board'){sc.innerHTML=boardHtml(it);}
 else if(ph.n==='strip'){}}
function l3(k,b,extra){return '<div class="cs-l3"><span class="cs-l3-k">'+k+'</span><b>'+b+'</b>'+(extra||'')+'</div>';}
function update(ph,f,t){var it=cur;if(ph.n==='clock'){var bar=root.querySelector('.cs-bar i'),tm=root.querySelector('.cs-timer');if(bar)bar.style.width=((1-f)*100).toFixed(1)+'%';if(tm){var s=Math.max(0,Math.round(150*(1-f)));tm.textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0');}}
 else if(ph.n==='podium'){var el=root.querySelector('.cs-typed');if(el){var n=Math.round(it.line.length*Math.min(1,f/0.62));if(el.textContent.length!==n)el.textContent=it.line.slice(0,n);}root.querySelector('.cs-dots').style.opacity=f>0.64?1:0;}
 else if(ph.n==='photo'){var fl=root.querySelector('.cs-flash'),r=rng('flash|'+Math.floor(t*9)+'|'+it.overall)();fl.style.opacity=r>0.62&&f<0.72?((r-0.62)*1.1).toFixed(2):'0';}
 if(ph.n!=='photo'){var fl2=root.querySelector('.cs-flash');if(fl2&&fl2.style.opacity!=='0')fl2.style.opacity='0';}}
function addTick(it){var p=it.p;if(tick.some(function(x){return x.year===it.year&&x.overall===it.overall;}))return;tick.push({year:it.year,overall:it.overall,owner:it.owner,name:p.name,pos:p.pos,league:p.league||''});if(tick.length>14)tick.shift();renderTick();}
function renderTick(){if(!root)return;root.querySelector('.cs-tick-list').innerHTML=tick.slice().reverse().map(function(x,i){return '<span class="'+(i===0?'cs-new':'')+'"><em>#'+x.overall+'</em><b>'+esc(x.owner)+'</b>'+esc(x.name)+' · '+esc(x.pos)+'</span>';}).join('');}
function card(it,mini){var p=it.p,x=X(),g=game(),tm=nmT(it.owner),lt=ltype(p),t=S.traits(seedOf(g),p,lt,Number(p.age)||18),chr=S.character(t),s=p.stats||{},stat=p.pos==='G'?(s.gp?s.gp+' GP · '+s.svp+' SV% · '+s.gaa+' GAA':''):(s.gp?s.gp+' GP · '+s.g+' G · '+s.a+' A · '+s.pts+' PTS':''),talk=p.ctfoDraft&&p.ctfoDraft.talk,user=it.kind==='user'||it.kind==='talk';
 var chip=!user&&talk&&!talk.pending?'<span class="cs-chip cs-'+(OUT[talk.outcome]||OUT.return)[1]+'">'+esc(S.outcomeTitle(talk,p))+'</span>':'';
 if(mini)return '<div class="cs-mini"><div class="cs-mini-crest">'+x.officeMark(it.owner,'cs-crest-mark')+'</div><div><p class="cs-kick">#'+it.overall+' · ROUND '+it.round+' · '+esc(tm.toUpperCase())+'</p><h3>'+esc(p.name)+'</h3><small>'+esc(p.pos)+' · '+esc(p.amateurTeam||'')+' ('+esc(p.league||'')+') · '+esc(S.tier(p))+'</small></div>'+chip+'</div>';
 var sr=p.scoutReport,ovr=sr&&sr.currentLow!=null?sr.currentLow+'–'+sr.currentHigh:sr?'?':String(p.ovr||'—'),pot=sr&&sr.low!=null?sr.low+'–'+sr.high:S.grade(p.potential);/* v9.1: scoutReport low/high is the POT range, currentLow/currentHigh the OVR range */
 return '<div class="cs-card"><aside class="cs-card-l"><div class="cs-crest">'+x.officeMark(it.owner,'cs-crest-mark')+'</div><b>#'+it.overall+'</b><small>ROUND '+it.round+' · PICK '+it.slot+'</small><small>'+esc(tm.toUpperCase())+'</small></aside><div class="cs-card-m"><p class="cs-kick">THE PICK</p><h1>'+esc(p.name)+'</h1><p class="cs-pos">'+esc(POSN[p.pos]||p.pos).toUpperCase()+' · '+esc(p.amateurTeam||'')+' · '+esc(p.league||'')+'</p>'+
  '<dl class="cs-facts"><div><dt>Height / Weight</dt><dd>'+ft(p.heightCm)+' · '+(p.weightKg?Math.round(p.weightKg*2.2046)+' lb':'—')+'</dd></div><div><dt>'+(p.pos==='G'?'Catches':'Shoots')+'</dt><dd>'+esc(p.shoots||'—')+'</dd></div><div><dt>Born</dt><dd>'+esc(p.ctfoDob||'—')+' · '+esc(S.birthplace(p))+'</dd></div><div><dt>Last season</dt><dd>'+esc(stat||'—')+'</dd></div></dl><p class="cs-blurb">'+esc(S.blurb(p))+'</p><p class="cs-char">Character: <b>'+esc(chr.join(', '))+'</b></p>'+chip+'</div>'+
  '<aside class="cs-card-r"><div><span>'+(sr?'SCOUT OVR':'OVR')+'</span><b>'+esc(ovr)+'</b></div><div><span>'+(sr&&sr.low!=null?'SCOUT POT':'POTENTIAL')+'</span><b>'+esc(pot)+'</b></div><div class="cs-tier"><span>PROJECTION</span><b>'+esc(S.tier(p))+'</b></div><div><span>AGE</span><b>'+esc(p.age||'—')+'</b></div></aside></div>';}
function order(it,p){var q=S.qById(p.ctfoDraft.talk.qid),r=rng('ans|'+q.id+'|'+p.id),a=[0,1,2,3];for(var i=3;i>0;i--){var j=Math.floor(r()*(i+1)),k=a[i];a[i]=a[j];a[j]=k;}return a;}
function questionHtml(it){var p=it.p,t=p.ctfoDraft&&p.ctfoDraft.talk,q=t&&S.qById(t.qid),g=game();if(!q)return '<div class="cs-panel"><p>No question available.</p><button type="button" class="cs-btn cs-gold" data-cs="skipq">Continue</button></div>';var trs=S.traits(seedOf(g),p,ltype(p),Number(p.age)||18);
 var ask=q.by==='player'?'<div class="cs-ask"><span class="cs-who">'+esc(p.name)+' asks you</span><blockquote>“'+esc(q.q)+'”</blockquote></div><p class="cs-sub">Your answer</p>':'<div class="cs-ask cs-you"><span class="cs-who">You ask '+esc(p.name.split(' ')[0])+'</span><blockquote>“'+esc(q.q)+'”</blockquote></div><div class="cs-ask cs-reply"><span class="cs-who">'+esc(p.name)+'</span><blockquote>“'+esc(q.reply)+'”</blockquote></div><p class="cs-sub">Your response</p>';
 return '<div class="cs-panel cs-q"><p class="cs-kick">ON STAGE · THE CONVERSATION · '+esc(q.cat.toUpperCase())+'</p>'+ask+'<div class="cs-answers">'+order(it,p).map(function(i,n){return '<button type="button" class="cs-answer" data-cs-answer="'+i+'"><em>'+'ABCD'[n]+'</em><span>'+esc(q.answers[i].text)+'</span></button>';}).join('')+'</div><p class="cs-note">What you say here moves his willingness to sign an entry-level contract now. Character: <b>'+esc(S.character(trs).join(', '))+'</b>.</p></div>';}
S.answer=function(i){if(!cur||cur.phases[cur.pi].n!=='question')return;var g=game(),p=cur.p,t=p.ctfoDraft&&p.ctfoDraft.talk,q=t&&S.qById(t.qid);if(!g||!q)return;cur.res=S.resolve(g,p,t.owner,t.year,t.overall,q,Number(i),true);cur.q=q;var skipped=skipCall(g,p);try{X().persist();}catch(e){console.error(e);}if(skipped){try{X().renderOffice();}catch(e){console.error(e);}}advance();};
/* v9.1: the base game's phone call is skipped when the stage conversation already happened for that pick (no double moment) */
function skipCall(g,p){var off=g&&g.offseason,c=off&&off.playerCall,D=DR();if(!c||!p||c.playerId!==p.id)return false;off.playerCall=null;if(D){D._round=null;if(off.phase==='draft'&&D.advanceDraftOnePick){try{D.advanceDraftOnePick(g);}catch(e){console.error(e);}}}S._callsSkipped=(S._callsSkipped||0)+1;return true;}
S._skipCall=skipCall;
function debriefHtml(it){var res=it.res,p=it.p,q=it.q;if(!res)return '';var ev=res.ev,t=res.traits,ex=S.explain(ev,res.evs,t,q),talk=res.talk,v=talk.verdict,o=OUT[talk.outcome]||OUT.return;
 var prof=TRAITS.map(function(tr){var val=t[tr[0]];return '<div class="cs-trait"><b>'+tr[1]+'</b><span class="cs-tbar"><i style="width:'+val+'%"></i></span><em>'+val+'</em><small>'+esc(S.traitLine(tr[0],val))+'</small></div>';}).join('');
 var best=ex.best?'<p><b>“'+esc(ex.best.text)+'”</b></p><p>'+esc(ex.best.why)+' It would have put his signing chance at '+pct(ex.best.pAfter)+'.</p>':'<p>You picked the best available answer for his personality.</p>';
 return '<div class="cs-panel cs-debrief"><header><div><p class="cs-kick">DEBRIEF · '+esc(p.name.toUpperCase())+'</p><h2>How that landed</h2></div><span class="cs-verdict cs-v-'+v.toLowerCase()+'">'+v.toUpperCase()+' ANSWER</span></header><div class="cs-db-grid"><section class="cs-profile"><h4>Personality profile</h4>'+prof+'</section><section class="cs-why"><h4>Your answer</h4><p class="cs-chosen">“'+esc(q.answers[talk.choice].text)+'”</p><h4>Why</h4><p>'+esc(ex.why)+'</p><h4>Best answer</h4>'+best+
  '<div class="cs-meter"><span>Signing chance</span><b>'+pct(talk.pBefore)+' → '+pct(talk.pAfter)+'</b><div class="cs-meter-bar"><i class="cs-m-after" style="width:'+pct(talk.pAfter)+'"></i><i class="cs-m-before" style="left:'+pct(talk.pBefore)+'"></i></div></div><div class="cs-outcome cs-'+o[1]+'"><b>'+esc(S.outcomeTitle(talk,p))+'</b><small>'+esc(S.outcomeDetail(talk,p,game()))+'</small></div></section></div><div class="cs-db-actions"><button type="button" class="cs-btn cs-gold" data-cs="continue">Continue →</button></div></div>';}
function boardHtml(it){var g=game(),x=X(),log=(g&&g.offseason&&g.offseason.draftLog||[]).filter(function(r){return r.overall<=it.overall;}).slice(-6).reverse(),st=g&&g.offseason&&g.offseason.liveDraft,nx=st&&st.order&&st.order[it.overall];
 return '<div class="cs-panel cs-board"><p class="cs-kick">DRAFT BOARD · ROUND '+it.round+'</p><div class="cs-board-list">'+log.map(function(r,i){return '<div class="'+(i===0?'cs-new':'')+'"><em>#'+r.overall+'</em><span class="cs-b-crest">'+x.officeMark(r.team,'cs-crest-mark')+'</span><b>'+esc(r.playerName)+'</b><small>'+esc(r.pos)+' · '+esc(r.teamName)+'</small></div>';}).join('')+'</div><div class="cs-next">'+(nx?'<span>UP NEXT</span><span class="cs-b-crest">'+x.officeMark(nx.owner,'cs-crest-mark')+'</span><b>'+esc(nmT(nx.owner))+'</b><small>#'+nx.overall+' · ROUND '+nx.round+'</small>':'<span>DRAFT COMPLETE</span><b>All seven rounds are in the books</b>')+'</div></div>';}
